"""
Django settings for webstats project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    raw = os.getenv(name)
    if raw is None:
        return bool(default)
    return str(raw).strip().lower() in {'1', 'true', 'yes', 'on'}

def _env_int(name, default):
    raw = os.getenv(name)
    if raw is None:
        return int(default)
    try:
        return int(str(raw).strip())
    except Exception:
        return int(default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'false').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-insecure-change-me'
    else:
        raise ImproperlyConfigured('SECRET_KEY es obligatorio cuando DEBUG=False')

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]
if not DEBUG and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS no puede contener "*" cuando DEBUG=False')

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

RENDER_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_HOSTNAME:
    if RENDER_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RENDER_HOSTNAME)
    render_origin = f'https://{RENDER_HOSTNAME}'
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

# En despliegues con dominio personalizado, el Origin/Referer puede no coincidir con RENDER_EXTERNAL_HOSTNAME.
# Para evitar 403 por CSRF al guardar tareas/acciones, añadimos automáticamente los hosts permitidos como orígenes confiables.
for _host in list(ALLOWED_HOSTS):
    _host = str(_host or '').strip()
    if not _host or _host == '*' or _host.startswith('.'):
        _host = _host.lstrip('.')
    if not _host or _host in {'localhost', '127.0.0.1'}:
        continue
    # Por seguridad la app debería ir en HTTPS, pero incluimos HTTP por si hay redirección/proxy intermedio.
    for _scheme in ('https', 'http'):
        _origin = f'{_scheme}://{_host}'
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'whitenoise.runserver_nostatic',
    'football',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Sesiones (login)
# - SESSION_COOKIE_AGE: segundos (por defecto Django: 1209600 = 2 semanas)
# - SESSION_SAVE_EVERY_REQUEST: renueva caducidad en cada request (expiración "deslizante")
# Nota: en producción preferimos caducidad más amplia y deslizante para evitar perder trabajo por expiración.
SESSION_COOKIE_AGE = _env_int('SESSION_COOKIE_AGE', 2592000)  # 30 días
SESSION_SAVE_EVERY_REQUEST = _env_bool('SESSION_SAVE_EVERY_REQUEST', True)
SESSION_EXPIRE_AT_BROWSER_CLOSE = _env_bool('SESSION_EXPIRE_AT_BROWSER_CLOSE', False)
SESSION_COOKIE_NAME = (os.getenv('SESSION_COOKIE_NAME') or 'webstats_sessionid').strip() or 'webstats_sessionid'
# Por compatibilidad: el frontend usa `csrftoken` (nombre estándar de Django) en fetch/XHR.
CSRF_COOKIE_NAME = (os.getenv('CSRF_COOKIE_NAME') or 'csrftoken').strip() or 'csrftoken'
SESSION_ENGINE_ENV = os.getenv('SESSION_ENGINE', '').strip()
if SESSION_ENGINE_ENV:
    SESSION_ENGINE = SESSION_ENGINE_ENV

if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', True)
    # Si se despliega sin HTTPS (p.ej. red local o proxy sin SSL), permitir desactivar cookies Secure
    # para evitar que la sesión no persista y obligue a loguearse continuamente.
    SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', SECURE_SSL_REDIRECT)
    CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', SECURE_SSL_REDIRECT)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ROOT_URLCONF = 'webstats.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'football.context_processors.workspace_access',
            ],
        },
    },
]

WSGI_APPLICATION = 'webstats.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=_env_int('DB_CONN_MAX_AGE', 600),
            ssl_require=_env_bool('DB_SSL_REQUIRE', (not DEBUG)),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Backend de sesión
# En despliegues con múltiples instancias + SQLite local, las sesiones en DB no se comparten y el usuario
# puede acabar redirigido a /login/ en cada request. Usamos cookies firmadas por defecto en ese caso.
if not SESSION_ENGINE_ENV:
    try:
        if not DEBUG and str(DATABASES.get('default', {}).get('ENGINE', '')).endswith('sqlite3'):
            SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
    except Exception:
        pass


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

USE_S3_MEDIA = os.getenv('USE_S3_MEDIA', 'false').lower() == 'true'
if USE_S3_MEDIA:
    aws_access_key_id = os.getenv('AWS_ACCESS_KEY_ID', '').strip()
    aws_secret_access_key = os.getenv('AWS_SECRET_ACCESS_KEY', '').strip()
    aws_storage_bucket_name = os.getenv('AWS_STORAGE_BUCKET_NAME', '').strip()
    aws_s3_region_name = os.getenv('AWS_S3_REGION_NAME', '').strip()
    if not aws_access_key_id or not aws_secret_access_key or not aws_storage_bucket_name or not aws_s3_region_name:
        raise ImproperlyConfigured(
            'Config S3 incompleta: define AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, '
            'AWS_STORAGE_BUCKET_NAME y AWS_S3_REGION_NAME cuando USE_S3_MEDIA=true.'
        )

    AWS_ACCESS_KEY_ID = aws_access_key_id
    AWS_SECRET_ACCESS_KEY = aws_secret_access_key
    AWS_STORAGE_BUCKET_NAME = aws_storage_bucket_name
    AWS_S3_REGION_NAME = aws_s3_region_name
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_ADDRESSING_STYLE = 'virtual'

    AWS_MEDIA_LOCATION = os.getenv('AWS_MEDIA_LOCATION', 'media').strip().strip('/')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN', '').strip()
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'region_name': AWS_S3_REGION_NAME,
                'default_acl': AWS_DEFAULT_ACL,
                'file_overwrite': AWS_S3_FILE_OVERWRITE,
                'querystring_auth': AWS_QUERYSTRING_AUTH,
                'location': AWS_MEDIA_LOCATION,
                'custom_domain': AWS_S3_CUSTOM_DOMAIN or None,
            },
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_MEDIA_LOCATION}/'
    else:
        MEDIA_URL = (
            f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'
            f'{AWS_MEDIA_LOCATION}/'
        )

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import dj_database_url
database_url = os.getenv('DATABASE_URL', '').strip()
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url, conn_max_age=600)
else:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

ALLOW_SQLITE_IN_PROD = os.getenv('ALLOW_SQLITE_IN_PROD', 'false').lower() == 'true'
if not DEBUG and DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3' and not ALLOW_SQLITE_IN_PROD:
    raise ImproperlyConfigured(
        'DATABASE_URL es obligatorio en producción. '
        'SQLite solo se permite con ALLOW_SQLITE_IN_PROD=true.'
    )

# Cache
# Por defecto Django usa DummyCache si no se define CACHES (no cachea nada) y las vistas de métricas
# recalculan todo en cada request.
#
# Importante: FileBasedCache puede bloquearse o ir lento en algunos entornos (I/O / locks).
# Usamos LocMemCache por defecto (rápido) y dejamos FileBasedCache como opción por env.
CACHE_BACKEND = (os.getenv('CACHE_BACKEND') or 'locmem').strip().lower()
CACHE_DEFAULT_TIMEOUT = _env_int('CACHE_DEFAULT_TIMEOUT', 3600)
_cache_max_entries = _env_int('CACHE_MAX_ENTRIES', 10000)
if CACHE_BACKEND in {'file', 'filebased'}:
    CACHE_DIR = (os.getenv('CACHE_DIR') or '/tmp/webstats-cache').strip() or '/tmp/webstats-cache'
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': CACHE_DIR,
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
            'OPTIONS': {
                'MAX_ENTRIES': _cache_max_entries,
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'webstats-locmem',
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
            'OPTIONS': {
                'MAX_ENTRIES': _cache_max_entries,
            },
        }
    }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django_error.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
