TASK_SURFACE_CHOICES = [
    ('natural_grass', 'Hierba natural'),
    ('hybrid_grass', 'Hierba híbrida'),
    ('artificial_turf', 'Césped artificial'),
    ('futsal', 'Pista futsal'),
    ('sand', 'Arena'),
    ('indoor', 'Indoor'),
    ('gym', 'Gimnasio'),
    ('dirt', 'Tierra'),
    ('street', 'Asfalto'),
]
TASK_PITCH_FORMAT_CHOICES = [
    ('11v11_full', '11v11 · Campo completo'),
    ('11v11_half', '11v11 · Medio campo'),
    ('9v9', '9v9'),
    ('8v8', '8v8'),
    ('7v7', '7v7'),
    ('5v5', '5v5'),
    ('abp', 'ABP'),
    ('specific_zone', 'Zona específica'),
]
TASK_GAME_PHASE_CHOICES = [
    ('organization_attack', 'Organización ofensiva'),
    ('organization_defense', 'Organización defensiva'),
    ('offensive_transition', 'Transición ofensiva'),
    ('defensive_transition', 'Transición defensiva'),
    ('set_pieces', 'ABP'),
]
TASK_METHODOLOGY_CHOICES = [
    ('analytical', 'Analítica'),
    ('integrated', 'Integrada'),
    ('global', 'Global'),
    ('competition', 'Competitiva'),
    ('coadjuvant', 'Coadyuvante'),
]
TASK_COMPLEXITY_CHOICES = [
    ('low', 'Baja'),
    ('medium', 'Media'),
    ('high', 'Alta'),
]
TASK_STRATEGY_CHOICES = [
    ('abp', 'Acciones a Balón Parado'),
    ('combined', 'Acciones Combinadas'),
    ('circuit', 'Circuito'),
    ('conservation', 'Conservación'),
    ('adapted', 'Juego Adaptado al Fútbol'),
    ('positional', 'Juego de Posición'),
    ('positional_specific', 'Juego de Posición Específico'),
    ('waves', 'Oleadas'),
    ('matches', 'Partidos'),
    ('possession', 'Posesión'),
    ('passing_wheel', 'Rueda de Pases'),
    ('reduced_games', 'Situaciones Reducidas'),
    ('lines_work', 'Trabajo de Líneas'),
]
TASK_COORDINATION_SKILLS_CHOICES = [
    ('offball', 'Actuación por Desmarcación'),
    ('start_stop', 'Arrancar/Frenar'),
    ('direction_change', 'Cambiar de Dirección'),
    ('carry', 'Conducción'),
    ('control', 'Control'),
    ('clearances', 'Despejes'),
    ('movements', 'Desplazamientos'),
    ('shots', 'Disparos'),
    ('tackles', 'Entrada'),
    ('balance', 'Equilibrarse'),
    ('turns', 'Giros'),
    ('interceptions', 'Intercepción'),
    ('pass', 'Pase'),
    ('protection', 'Protección'),
    ('dribble', 'Regate'),
    ('jumps', 'Saltos'),
]
TASK_TACTICAL_INTENT_CHOICES = [
    ('1v1', '1 vs 1'),
    ('2v1', '2 vs 1'),
    ('2v2', '2 vs 2'),
    ('3v3', '3 vs 3'),
    ('4v4', '4 vs 4'),
    ('abp_def', 'ABP Defensiva'),
    ('abp_att', 'ABP Ofensiva'),
    ('width', 'Amplitud'),
    ('supports', 'Apoyos'),
    ('organized_attack', 'Ataque Organizado'),
    ('cover', 'Cobertura'),
    ('keep', 'Conservar'),
    ('counter', 'Contraataque'),
    ('def_build', 'Defensa Inicio de Juego'),
    ('def_direct', 'Defensa de Juego Directo'),
    ('def_organized', 'Defensa Organizada'),
    ('runs', 'Desmarques'),
    ('split', 'Dividir'),
    ('avoid_progress', 'Evitar Progresión'),
    ('phase_def', 'Fase Defensiva'),
    ('phase_att', 'Fase Ofensiva'),
    ('fix', 'Fijar'),
    ('finish', 'Finalizar'),
    ('build', 'Inicio de Juego'),
    ('direct', 'Juego Directo'),
    ('maintain', 'Mantener'),
    ('marking', 'Marcaje'),
    ('orient', 'Orientar'),
    ('swap', 'Permuta'),
    ('press', 'Presionar'),
    ('first_attacker', 'Primer Atacante'),
    ('first_defender', 'Primer Defensor'),
    ('depth', 'Profundidad'),
    ('progress', 'Progresar'),
    ('protect_goal', 'Proteger Portería'),
    ('recover', 'Recuperar'),
    ('restart', 'Reinicio de Juego'),
    ('retreat', 'Replegar'),
    ('second_attacker', 'Segundo Atacante'),
    ('second_defender', 'Segundo Defensor'),
    ('delay', 'Temporizar'),
    ('third_attacker', 'Tercer Atacante'),
    ('third_defender', 'Tercer Defensor'),
]
TASK_DYNAMICS_CHOICES = [
    ('adm', 'ADM'),
    ('extensive', 'Extensiva'),
    ('strength', 'Fuerza'),
    ('intense_action', 'Intensiva (acción)'),
    ('intense_interaction', 'Intensiva (interacción)'),
    ('recovery', 'Recuperación'),
    ('endurance', 'Resistencia'),
    ('speed', 'Velocidad'),
]
TASK_STRUCTURE_CHOICES = [
    ('complete', 'Estructura Completa'),
    ('intersectorial', 'Intersectorial'),
    ('sectorial', 'Sectorial'),
]
TASK_COORDINATION_CHOICES = [
    ('team', 'Coordinación Equipo'),
    ('player', 'Coordinación Jugador/a'),
    ('players', 'Coordinación Jugadores/as'),
]
TASK_USEFULNESS_CHOICES = [
    ('1', '1 · Baja'),
    ('2', '2'),
    ('3', '3 · Media'),
    ('4', '4'),
    ('5', '5 · Top'),
]
TASK_CONSTRAINT_CHOICES = [
    ('two_touches', '2 toques'),
    ('one_touch_zone', '1 toque zona final'),
    ('mandatory_switch', 'Cambio de orientación obligatorio'),
    ('finish_under_10', 'Finalizar < 10 segundos'),
    ('press_6_seconds', 'Presionar 6 segundos tras pérdida'),
    ('bonus_recovery_high', 'Bonus por recuperación alta'),
    ('max_3_passes_before_finish', 'Máx. 3 pases antes de finalizar'),
]
