from django.urls import path

from . import academy_views, account_views, billing_views, kit2d_views
from . import pwa as pwa_views
from . import (
    season_diagnostics,
    task_token_image,
    avatar_data_views,
    season_wizard_views,
    session_pdf,
    tactical_plan_views,
    tactical_views,
    task_board_snapshot,
    video_studio_views,
    views,
    workspace_views,
)

urlpatterns = [
    path("manifest.webmanifest", pwa_views.pwa_manifest, name="pwa-manifest"),
    path("sw.js", pwa_views.pwa_service_worker, name="pwa-sw"),
    path("offline/", pwa_views.pwa_offline, name="pwa-offline"),
    path("2j/", views.product_landing_page, name="product-landing"),
    path("signup/", views.public_signup_page, name="signup"),
    path("onboarding/", views.club_onboarding_page, name="club-onboarding"),
    path("onboarding/season/", season_wizard_views.club_season_wizard, name="club-season-wizard"),
    path("team/<int:team_id>/crest.svg", views.team_crest_svg, name="team-crest-svg"),
    path("", views.dashboard_page, name="dashboard-home"),
    path("partido/", views.match_hub_page, name="match-hub"),
    path("partido/crear/", views.match_hub_create_match, name="match-hub-create"),
    path("partido/guardar/", views.match_hub_finalize_match, name="match-hub-finalize"),
    path("buscar/", views.search_page, name="search-page"),
    path("calendario/club.ics", views.team_calendar_ics, name="team-calendar-ics"),
    path("api/session/keepalive/", views.session_keepalive, name="session-keepalive"),
    path("api/build/", views.public_build_info, name="public-build-info"),
    # Alias corto para debug/healthchecks en producción (p.ej. /build).
    path("build/", views.public_build_info, name="public-build-info-short"),
    path("api/search/", views.search_api, name="search-api"),
    path("api/rivals/roster/", views.rival_roster_api, name="rival-roster-api"),
    path("billing/", billing_views.billing_page, name="billing"),
    path("api/billing/checkout/", billing_views.billing_checkout_session_api, name="billing-checkout-session"),
    path("api/billing/portal/", billing_views.billing_portal_session_api, name="billing-portal-session"),
    path("api/billing/apple/receipt/", billing_views.apple_receipt_api, name="billing-apple-receipt"),
    path("stripe/webhook/", billing_views.stripe_webhook, name="stripe-webhook"),
    path("api/workspace/active/", workspace_views.workspace_set_active_workspace, name="workspace-active"),
    path("api/workspace/active-team/", workspace_views.workspace_set_active_team, name="workspace-active-team"),
    path("api/workspace/preferences/get/", workspace_views.workspace_preference_get_api, name="workspace-pref-get"),
    path("api/workspace/preferences/set/", workspace_views.workspace_preference_set_api, name="workspace-pref-set"),
    path("api/kits/2d/generate/", kit2d_views.kit2d_generate_api, name="kit2d-generate-api"),
    path("tools/kit2d/", kit2d_views.kit2d_generator_page, name="kit2d-generator"),
    path("academia/", academy_views.academy_home_page, name="academy-home"),
    path("academia/leccion/<int:lesson_id>/", academy_views.academy_lesson_page, name="academy-lesson"),
    path("api/academy/today/", academy_views.academy_today_api, name="academy-today-api"),
    path("api/academy/answer/", academy_views.academy_answer_api, name="academy-answer-api"),
    path("api/academy/complete/", academy_views.academy_complete_api, name="academy-complete-api"),
    path("api/workspace/sync/", workspace_views.workspace_sync_competition_api, name="workspace-sync-competition"),
    path("team/<int:team_id>/cover/", views.team_cover_image_file, name="team-cover-image-file"),
    path("platform/", views.platform_overview_page, name="platform-overview"),
    path("platform/asistente/", views.platform_assistant_page, name="platform-assistant"),
    path("platform/clear/", views.platform_workspace_clear_page, name="platform-workspace-clear"),
    path(
        "platform/workspaces/<int:workspace_id>/",
        views.platform_workspace_detail_page,
        name="platform-workspace-detail",
    ),
    path(
        "platform/workspaces/<int:workspace_id>/teams/<int:team_id>/",
        views.platform_workspace_team_detail_page,
        name="platform-workspace-team-detail",
    ),
    path(
        "platform/workspaces/<int:workspace_id>/delete/",
        views.platform_workspace_delete_page,
        name="platform-workspace-delete",
    ),
    path(
        "platform/workspaces/<int:workspace_id>/enter/",
        views.platform_workspace_enter_page,
        name="platform-workspace-enter",
    ),
    path("task-studio/", views.task_studio_home_page, name="task-studio-home"),
    path("task-studio/profile/", views.task_studio_profile_page, name="task-studio-profile"),
    path("task-studio/roster/", views.task_studio_roster_page, name="task-studio-roster"),
    path("task-studio/task/create/", views.task_studio_task_create, name="task-studio-task-create"),
    path("task-studio/task/<int:task_id>/delete/", views.task_studio_task_delete, name="task-studio-task-delete"),
    path(
        "task-studio/task/<int:task_id>/duplicate/", views.task_studio_task_duplicate, name="task-studio-task-duplicate"
    ),
    path("task-studio/task/pdf-preview/", views.task_studio_task_pdf_preview, name="task-studio-task-pdf-preview"),
    path("api/dashboard/", views.dashboard_data, name="dashboard-data"),
    path("api/dashboard/refresh/", views.refresh_scraping, name="dashboard-refresh"),
    path("media/home-carousel/<int:image_id>/", views.home_carousel_image_file, name="home-carousel-image-file"),
    path("media/pdf-assets/<int:asset_id>/", views.pdf_graphic_asset_file, name="pdf-graphic-asset-file"),
    path("players/", views.player_dashboard_page, name="player-dashboard"),
    path("players/notifications/read/", views.player_notifications_mark_read, name="player-notifications-read"),
    path("player/<int:player_id>/lesiones/<int:record_id>/", views.player_injury_detail_page, name="player-injury-detail"),
    path("player/<int:player_id>/comunicacion/<int:comm_id>/", views.player_communication_detail_page, name="player-communication-detail"),
    path("player/<int:player_id>/objetivo/<int:objective_id>/", views.player_objective_detail_page, name="player-objective-detail"),
    path("player/<int:player_id>/sesion/<int:session_id>/", views.player_session_detail_page, name="player-session-detail"),
    path("player/<int:player_id>/avatar.png", views.player_avatar_recolored, name="player-avatar-recolored"),
    path("players/attendance/mark/", views.player_attendance_mark, name="player-attendance-mark"),
    path("players/videos/", views.player_video_library_page, name="player-video-library"),
    path("players/videos/view/<int:video_id>/", views.player_video_view_page, name="player-video-view"),
    path("players/videos/clip/view/<int:clip_id>/", views.player_video_clip_view_page, name="player-video-clip-view"),
    path("players/videos/inbox/", views.player_video_inbox_page, name="player-video-inbox"),
    path("players/videos/inbox/open/<int:item_id>/", views.player_video_inbox_open, name="player-video-inbox-open"),
    path(
        "players/videos/clip/<int:item_id>/",
        views.player_video_inbox_clip_view_page,
        name="player-video-inbox-clip-view",
    ),
    path(
        "players/videos/export/<int:item_id>/",
        views.player_video_inbox_export_view_page,
        name="player-video-inbox-export-view",
    ),
    path(
        "players/videos/export/<int:item_id>/stream/",
        views.player_video_inbox_export_stream,
        name="player-video-inbox-export-stream",
    ),
    path(
        "players/videos/playlist/<int:item_id>/",
        views.player_video_inbox_playlist_view_page,
        name="player-video-inbox-playlist-view",
    ),
    path(
        "players/videos/report/<int:item_id>/",
        views.player_video_inbox_report_view_page,
        name="player-video-inbox-report",
    ),
    path("coach/agenda/", views.team_agenda_page, name="team-agenda"),
    path("coach/informes/", views.reports_hub_page, name="reports-hub"),
    path("coach/informes/jugadores/zip/", views.player_reports_zip, name="player-reports-zip"),
    path("coach/informes/jugadores/evolucion/zip/", views.player_evolution_zip, name="player-evolution-zip"),
    path("coach/informes/lineas/pdf/", views.squad_lines_report_pdf, name="squad-lines-report-pdf"),
    path("coach/informes/equipo/", views.team_report_page, name="team-report-page"),
    path("coach/informes/direccion/", views.direction_report_page, name="direction-report-page"),
    path("coach/informes/direccion/pdf/", views.direction_report_pdf, name="direction-report-pdf"),
    path("coach/dashboard/", views.kpi_dashboard_page, name="kpi-dashboard"),
    path("direccion/", views.scouting_board_page, name="scouting-board"),
    path("direccion/shortlist/", views.scouting_shortlist_page, name="scouting-shortlist"),
    path("direccion/campo.png", views.scouting_pitch_png, name="scouting-pitch-png"),
    path("direccion/pizarra/guardar/", views.scouting_pitch_board_save, name="scouting-pitch-board-save"),
    path("coach/rivales/importar-liga/", views.rival_league_import, name="rival-league-import"),
    path("coach/rivales/importar-liga/estado/", views.rival_league_import_status, name="rival-league-import-status"),
    path("coach/rivales/ingesta/", views.rival_squad_ingest, name="rival-squad-ingest"),
    # Ingesta desde el agente que corre en una IP residencial (token, sin sesion).
    path("api/rivales/ingesta/", views.rival_squad_ingest_agent, name="rival-squad-ingest-agent"),
    path("coach/rivales/identidad/", views.rival_team_identity, name="rival-team-identity"),
    path("coach/rivales/", views.rival_players_index, name="rival-players-index"),
    path("coach/rivales/equipo/<int:team_id>/", views.rival_team_squad, name="rival-team-squad"),
    path("coach/rivales/jugador/<int:rival_player_id>/", views.rival_player_detail, name="rival-player-detail"),
    path("coach/rivales/jugador/<int:rival_player_id>/objetivo/", views.rival_player_make_target, name="rival-player-make-target"),
    path("coach/rivales/jugador/<int:rival_player_id>/vincular/", views.rival_player_link_own, name="rival-player-link-own"),
    path("direccion/<int:target_id>/", views.scouting_target_detail_page, name="scouting-target-detail"),
    path("direccion/<int:target_id>/pdf/", views.scouting_target_pdf, name="scouting-target-pdf"),
    path("coach/informes/equipo/pdf/", views.team_season_report_pdf, name="team-season-report-pdf"),
    path("coach/informes/partido/", views.match_staff_report_page, name="match-staff-report"),
    path("coach/informes/partido/pdf/", views.match_staff_report_pdf, name="match-staff-report-pdf"),
    path(
        "api/match/postmatch/to-blueprints/",
        views.match_postmatch_pro_to_blueprints_api,
        name="match-postmatch-pro-to-blueprints-api",
    ),
    path("admin-tools/", views.admin_page, name="admin-page"),
    path("invitation/<str:token>/", views.invitation_accept_page, name="user-invite-accept"),
    path("share/task-pdf/<str:token>/", views.share_task_pdf_page, name="share-task-pdf"),
    path("api/share/task-pdf/create/", views.share_task_pdf_create, name="share-task-pdf-create"),
    path("share/task-simulation/<str:token>/", views.share_task_simulation_page, name="share-task-simulation"),
    path("api/share/task-simulation/create/", views.share_task_simulation_create, name="share-task-simulation-create"),
    path(
        "share/tactical-playbook/<str:token>/",
        tactical_views.share_tactical_playbook_clip_page,
        name="share-tactical-playbook-clip",
    ),
    path(
        "api/share/tactical-playbook/create/",
        tactical_views.tactical_playbook_clip_share_create,
        name="share-tactical-playbook-clip-create",
    ),
    path("share/convocation-pdf/<str:token>/", views.share_convocation_pdf_page, name="share-convocation-pdf"),
    path("share/video-clip/<str:token>/", views.share_video_clip_page, name="share-video-clip"),
    path("share/video-clip/<str:token>/stream/", views.share_video_clip_stream, name="share-video-clip-stream"),
    path("share/video-report/<str:token>/", views.share_video_report_page, name="share-video-report"),
    path("share/video-report/<str:token>/pdf/", views.share_video_report_pdf, name="share-video-report-pdf"),
    path("share/video-playlist/<str:token>/", views.share_video_playlist_page, name="share-video-playlist"),
    path(
        "share/video-playlist/<str:token>/stream/",
        views.share_video_playlist_stream,
        name="share-video-playlist-stream",
    ),
    path("share/video-export/<str:token>/", views.share_video_export_page, name="share-video-export"),
    path("share/video-export/<str:token>/stream/", views.share_video_export_stream, name="share-video-export-stream"),
    path("api/share/convocation-pdf/create/", views.share_convocation_pdf_create, name="share-convocation-pdf-create"),
    path("api/share/video-clip/create/", views.share_video_clip_create, name="share-video-clip-create"),
    path("api/share/video-report/create/", views.share_video_report_create, name="share-video-report-create"),
    path("api/share/video-playlist/create/", views.share_video_playlist_create, name="share-video-playlist-create"),
    path("api/share/revoke/<str:token>/", views.share_link_revoke, name="share-link-revoke"),
    path("api/system/diagnostics/", views.system_diagnostics, name="system-diagnostics"),
    path("api/system/healthcheck/", views.system_healthcheck_api, name="system-healthcheck-api"),
    path("api/system/settings/set/", views.system_setting_set_api, name="system-setting-set-api"),
    path("legal/privacidad/", views.privacy_policy_page, name="privacy-policy"),
    path("legal/terminos/", views.terms_page, name="terms-page"),
    path("support/", views.support_page, name="support-page"),
    path("account/", views.account_page, name="account-page"),
    path("account/delete/", views.account_delete, name="account-delete"),
    # Verificación de email (Fase 2). 'reenviar' va ANTES que <token> para no capturarlo como token.
    path("verify-email/reenviar/", account_views.resend_email_verification, name="resend_email_verification"),
    path("verify-email/<str:token>/", account_views.verify_email, name="verify_email"),
    # Fase 3: gestión de miembros del club (owner/admin).
    path("coach/miembros/", account_views.workspace_members_page, name="workspace-members"),
    path("coach/portal-jugador/", account_views.player_portal_settings_page, name="player-portal-settings"),
    path("coach/miembros/<int:membership_id>/accesos/", account_views.workspace_member_access_page, name="workspace-member-access"),
    # Fase 6: espacio propio del jugador.
    path("mi-espacio/", account_views.player_home_page, name="player-home"),
    path("api/system/kpi-audit/", views.kpi_audit, name="kpi-audit"),
    path("api/analysis/rival-form/", views.analysis_rival_form_api, name="analysis-rival-form-api"),
    path(
        "api/analysis/rival-report/to-blueprints/",
        views.analysis_rival_report_to_blueprints_api,
        name="analysis-rival-report-to-blueprints-api",
    ),
    path("analysis/video/<int:video_id>/", video_studio_views.analysis_video_studio_page, name="analysis-video-studio"),
    path("analysis/video/clip/<int:clip_id>/", views.analysis_video_clip_view_page, name="analysis-video-clip-view"),
    path(
        "analysis/video/export/<int:export_id>/",
        views.analysis_video_export_view_page,
        name="analysis-video-export-view",
    ),
    path(
        "analysis/video/export/<int:export_id>/stream/",
        views.analysis_video_export_stream,
        name="analysis-video-export-stream",
    ),
    path(
        "analysis/video/playlist/inbox/<int:item_id>/",
        views.analysis_video_inbox_playlist_view_page,
        name="analysis-video-inbox-playlist-view",
    ),
    path(
        "analysis/video/report/inbox/<int:item_id>/",
        views.analysis_video_inbox_report,
        name="analysis-video-inbox-report",
    ),
    path("coach/kpis/", views.kpi_explorer_page, name="kpi-explorer"),
    path(
        "api/analysis/video-studio/projects/",
        video_studio_views.analysis_video_studio_projects_api,
        name="analysis-video-studio-projects-api",
    ),
    path(
        "api/analysis/video-studio/projects/save/",
        video_studio_views.analysis_video_studio_project_save_api,
        name="analysis-video-studio-project-save-api",
    ),
    path(
        "api/analysis/video-studio/projects/delete/",
        video_studio_views.analysis_video_studio_project_delete_api,
        name="analysis-video-studio-project-delete-api",
    ),
    path(
        "api/analysis/video-studio/clips/",
        video_studio_views.analysis_video_studio_clips_api,
        name="analysis-video-studio-clips-api",
    ),
    path(
        "api/analysis/video-studio/clips/save/",
        video_studio_views.analysis_video_studio_clip_save_api,
        name="analysis-video-studio-clip-save-api",
    ),
    path(
        "api/analysis/video-studio/clips/delete/",
        video_studio_views.analysis_video_studio_clip_delete_api,
        name="analysis-video-studio-clip-delete-api",
    ),
    path(
        "api/analysis/video-studio/voiceovers/",
        video_studio_views.analysis_video_studio_voiceovers_api,
        name="analysis-video-studio-voiceovers-api",
    ),
    path(
        "api/analysis/video-studio/voiceovers/upload/",
        video_studio_views.analysis_video_studio_voiceover_upload_api,
        name="analysis-video-studio-voiceover-upload-api",
    ),
    path(
        "api/analysis/video-studio/voiceovers/delete/",
        video_studio_views.analysis_video_studio_voiceover_delete_api,
        name="analysis-video-studio-voiceover-delete-api",
    ),
    path(
        "api/analysis/video-studio/music/",
        video_studio_views.analysis_video_studio_music_api,
        name="analysis-video-studio-music-api",
    ),
    path(
        "api/analysis/video-studio/music/upload/",
        video_studio_views.analysis_video_studio_music_upload_api,
        name="analysis-video-studio-music-upload-api",
    ),
    path(
        "api/analysis/video-studio/music/delete/",
        video_studio_views.analysis_video_studio_music_delete_api,
        name="analysis-video-studio-music-delete-api",
    ),
    path(
        "api/analysis/video-studio/assign/",
        video_studio_views.analysis_video_studio_assign_api,
        name="analysis-video-studio-assign-api",
    ),
    path(
        "api/analysis/video-studio/video/trim/",
        video_studio_views.analysis_video_studio_video_trim_api,
        name="analysis-video-studio-video-trim-api",
    ),
    path(
        "api/analysis/video-studio/timeline/",
        video_studio_views.analysis_video_studio_timeline_api,
        name="analysis-video-studio-timeline-api",
    ),
    path(
        "api/analysis/video-studio/timeline/save/",
        video_studio_views.analysis_video_studio_timeline_save_api,
        name="analysis-video-studio-timeline-save-api",
    ),
    path(
        "api/analysis/video-studio/timeline/delete/",
        video_studio_views.analysis_video_studio_timeline_delete_api,
        name="analysis-video-studio-timeline-delete-api",
    ),
    path(
        "api/analysis/video-studio/timeline/export/",
        video_studio_views.analysis_video_studio_timeline_export_api,
        name="analysis-video-studio-timeline-export-api",
    ),
    path(
        "api/analysis/video-studio/timeline/import/",
        video_studio_views.analysis_video_studio_timeline_import_api,
        name="analysis-video-studio-timeline-import-api",
    ),
    path(
        "api/analysis/video-studio/timeline/clear/",
        video_studio_views.analysis_video_studio_timeline_clear_api,
        name="analysis-video-studio-timeline-clear-api",
    ),
    path(
        "api/analysis/video-studio/review/",
        video_studio_views.analysis_video_studio_review_api,
        name="analysis-video-studio-review-api",
    ),
    path(
        "api/analysis/video-studio/ocr/dorsal/",
        video_studio_views.analysis_video_studio_ocr_dorsal_api,
        name="analysis-video-studio-ocr-dorsal-api",
    ),
    path("api/kpi-explorer/options/", views.kpi_explorer_options_api, name="kpi-explorer-options-api"),
    path("api/kpi-explorer/query/", views.kpi_explorer_query_api, name="kpi-explorer-query-api"),
    path("api/kpi-explorer/sources/", views.kpi_explorer_sources_api, name="kpi-explorer-sources-api"),
    path("api/kpi-explorer/pdf/", views.kpi_explorer_pdf_api, name="kpi-explorer-pdf-api"),
    path(
        "api/analysis/video-studio/export/pdf/",
        video_studio_views.analysis_video_studio_export_pdf_api,
        name="analysis-video-studio-export-pdf-api",
    ),
    path(
        "api/analysis/video-studio/export/package/",
        video_studio_views.analysis_video_studio_export_package_api,
        name="analysis-video-studio-export-package-api",
    ),
    path(
        "api/analysis/video-studio/export/upload/",
        video_studio_views.analysis_video_studio_export_upload_api,
        name="analysis-video-studio-export-upload-api",
    ),
    path(
        "api/analysis/video-studio/export/server/",
        video_studio_views.analysis_video_studio_export_server_api,
        name="analysis-video-studio-export-server-api",
    ),
    path(
        "api/analysis/video-studio/export/server-playlist/",
        video_studio_views.analysis_video_studio_export_server_playlist_api,
        name="analysis-video-studio-export-server-playlist-api",
    ),
    path(
        "api/analysis/video-studio/export/jobs/create/",
        video_studio_views.analysis_video_studio_export_job_create_api,
        name="analysis-video-studio-export-job-create-api",
    ),
    path(
        "api/analysis/video-studio/export/jobs/status/",
        video_studio_views.analysis_video_studio_export_job_status_api,
        name="analysis-video-studio-export-job-status-api",
    ),
    path(
        "api/analysis/video-studio/export/jobs/cancel/",
        video_studio_views.analysis_video_studio_export_job_cancel_api,
        name="analysis-video-studio-export-job-cancel-api",
    ),
    path(
        "api/analysis/video-studio/report/pdf/",
        video_studio_views.analysis_video_studio_report_pdf_api,
        name="analysis-video-studio-report-pdf-api",
    ),
    path(
        "api/analysis/video-studio/ai/",
        video_studio_views.analysis_video_studio_ai_api,
        name="analysis-video-studio-ai-api",
    ),
    path(
        "api/analysis/video-studio/ai/track/",
        video_studio_views.analysis_video_studio_ai_track_api,
        name="analysis-video-studio-ai-track-api",
    ),
    path(
        "api/analysis/video-studio/ai/pro/",
        video_studio_views.analysis_video_studio_ai_pro_api,
        name="analysis-video-studio-ai-pro-api",
    ),
    path(
        "api/analysis/video-studio/autocut/",
        video_studio_views.analysis_video_studio_autocut_api,
        name="analysis-video-studio-autocut-api",
    ),
    path(
        "api/analysis/video-studio/share-links/",
        video_studio_views.analysis_video_studio_share_links_api,
        name="analysis-video-studio-share-links-api",
    ),
    path(
        "api/analysis/video-studio/frame-capture/",
        video_studio_views.analysis_video_studio_frame_capture_api,
        name="analysis-video-studio-frame-capture-api",
    ),
    path(
        "api/analysis/video-studio/track/players/",
        video_studio_views.analysis_video_studio_track_players_api,
        name="analysis-video-studio-track-players-api",
    ),
    path(
        "api/analysis/video-inbox/recipients/",
        views.analysis_video_inbox_recipients_api,
        name="analysis-video-inbox-recipients-api",
    ),
    path("api/analysis/video-inbox/send/", views.analysis_video_inbox_send_api, name="analysis-video-inbox-send-api"),
    path(
        "api/analysis/video-inbox/comments/",
        views.analysis_video_inbox_comments_api,
        name="analysis-video-inbox-comments-api",
    ),
    path(
        "api/analysis/rival-videos/chunk/init/",
        views.analysis_rival_video_chunk_init_api,
        name="analysis-rival-video-chunk-init-api",
    ),
    path(
        "api/analysis/rival-videos/chunk/put/",
        views.analysis_rival_video_chunk_put_api,
        name="analysis-rival-video-chunk-put-api",
    ),
    path(
        "api/analysis/rival-videos/chunk/finish/",
        views.analysis_rival_video_chunk_finish_api,
        name="analysis-rival-video-chunk-finish-api",
    ),
    path(
        "api/analysis/rival-videos/import-youtube/",
        views.analysis_rival_video_import_youtube_api,
        name="analysis-rival-video-import-youtube-api",
    ),
    path("api/pdf-assets/upload/", views.pdf_graphic_asset_upload, name="pdf-graphic-asset-upload"),
    path("api/pdf-assets/delete/", views.pdf_graphic_asset_delete_api, name="pdf-graphic-asset-delete-api"),
    path(
        "api/task-resource-library/visibility/",
        views.task_resource_library_visibility_api,
        name="task-resource-library-visibility-api",
    ),
    path(
        "api/task-assistant/blueprints/",
        tactical_views.task_assistant_blueprints_api,
        name="task-assistant-blueprints-api",
    ),
    path(
        "api/task-assistant/blueprints/save/",
        tactical_views.task_assistant_blueprint_save_api,
        name="task-assistant-blueprint-save-api",
    ),
    path(
        "api/task-assistant/knowledge/",
        tactical_views.task_assistant_knowledge_api,
        name="task-assistant-knowledge-api",
    ),
    path(
        "api/task-assistant/knowledge/upload/",
        tactical_views.task_assistant_knowledge_upload_api,
        name="task-assistant-knowledge-upload-api",
    ),
    path(
        "api/tactical-playbook/clips/", tactical_views.tactical_playbook_clips_api, name="tactical-playbook-clips-api"
    ),
    path(
        "api/tactical-playbook/clips/save/",
        tactical_views.tactical_playbook_clip_save_api,
        name="tactical-playbook-clip-save-api",
    ),
    path(
        "api/tactical-playbook/tasks/save/",
        tactical_views.tactical_playbook_task_save_api,
        name="tactical-playbook-task-save-api",
    ),
    path(
        "api/tactical-playbook/clips/delete/",
        tactical_views.tactical_playbook_clip_delete_api,
        name="tactical-playbook-clip-delete-api",
    ),
    path(
        "api/tactical-playbook/clips/favorite/",
        tactical_views.tactical_playbook_clip_favorite_api,
        name="tactical-playbook-clip-favorite-api",
    ),
    path(
        "api/tactical-playbook/clips/clone/",
        tactical_views.tactical_playbook_clip_clone_api,
        name="tactical-playbook-clip-clone-api",
    ),
    path(
        "api/tactical-playbook/teams/", tactical_views.tactical_playbook_teams_api, name="tactical-playbook-teams-api"
    ),
    path(
        "api/tactical-playbook/versions/",
        tactical_views.tactical_playbook_versions_api,
        name="tactical-playbook-versions-api",
    ),
    path("coach/", views.coach_overview_page, name="coach-detail"),
    path("coach/asistente/", views.coach_assistant_api, name="coach-assistant"),
    path("player/<int:player_id>/", views.player_detail_page, name="player-detail"),
    path("player/<int:player_id>/photo/", views.player_photo_file, name="player-photo-file"),
    path("player/<int:player_id>/license/", views.player_license_file, name="player-license-file"),
    path("player/<int:player_id>/editar/", views.player_edit_page, name="player-edit"),
    path("player/<int:player_id>/valoracion/nueva/", views.player_evaluation_new_page, name="player-evaluation-new"),
    path("player/<int:player_id>/formulario/<str:key>/", views.player_form_page, name="player-form"),
    path("player/<int:player_id>/pdf/", views.player_pdf, name="player-pdf"),
    path("player/<int:player_id>/evolucion/pdf/", views.player_evolution_pdf, name="player-evolution-pdf"),
    path(
        "player/<int:player_id>/informe/editar/", views.player_season_report_edit_page, name="player-season-report-edit"
    ),
    path(
        "player/<int:player_id>/evaluacion/<int:evaluation_id>/informe/",
        views.player_evaluation_report_page,
        name="player-evaluation-report",
    ),
    path("player/<int:player_id>/match/<int:match_id>/", views.player_match_stats_page, name="player-match-stats"),
    path(
        "player/<int:player_id>/match/<int:match_id>/informe.pdf",
        views.player_match_report_pdf,
        name="player-match-report-pdf",
    ),
    path("match/<int:match_id>/", views.match_stats_page, name="match-stats"),
    path("coach/partidos/<int:match_id>/editar/", views.match_editor_page, name="match-editor"),
    path("incidencias/", views.incident_page, name="incident-page"),
    path("registro-acciones/", views.match_action_page, name="match-action-page"),
    path("registro-acciones/quick-buttons/", views.matchday_quick_buttons_api, name="matchday-quick-buttons-api"),
    path("registro-acciones/guardar/", views.register_match_action, name="match-action-record"),
    path("registro-acciones/bulk-add/", views.bulk_add_match_actions, name="match-action-bulk-add"),
    path("registro-acciones/lineup/save/", views.save_match_lineup, name="match-lineup-save"),
    path("registro-acciones/lineup/publish/", views.publish_initial_eleven, name="initial-eleven-publish"),
    path("registro-acciones/lineup/get/", views.get_match_lineup, name="match-lineup-get"),
    path("registro-acciones/rival-lineup/save/", views.save_match_rival_lineup, name="match-rival-lineup-save"),
    path("registro-acciones/rival-lineup/get/", views.get_match_rival_lineup, name="match-rival-lineup-get"),
    path("registro-acciones/video/links/", views.match_video_links_api, name="match-video-links-api"),
    path("registro-acciones/video/marker/", views.match_video_marker_api, name="match-video-marker-api"),
    path("registro-acciones/eliminar/", views.delete_match_action, name="match-action-delete"),
    path("registro-acciones/actualizar/", views.update_match_action, name="match-action-update"),
    path("registro-acciones/impacto/", views.update_match_action_impact, name="match-action-impact"),
    path("registro-acciones/eventos/", views.match_actions_events_api, name="match-actions-events-api"),
    path("registro-acciones/partido/guardar/", views.save_match_info, name="match-info-save"),
    path("registro-acciones/finalizar/", views.finalize_match_actions, name="match-action-finalize"),
    path("registro-acciones/reiniciar/", views.reset_match_action_register, name="match-action-reset"),
    path("registro-acciones/acta/", views.match_report_pdf, name="match-report-pdf"),
    path("convocatoria/", views.convocation_page, name="convocation"),
    path("convocatoria/save/", views.save_convocation, name="convocation-save"),
    path("convocatoria/pdf/", views.convocation_pdf, name="convocation-pdf"),
    path("convocatoria/arbitro/pdf/", views.convocation_referee_pdf, name="convocation-referee-pdf"),
    path("pdf/viewer/", views.pdf_viewer_page, name="pdf-viewer"),
    path("api/system/guard-chat/", views.system_guard_chat_api, name="system-guard-chat-api"),
    path("api/system/guard-operator/", views.system_guard_operator_api, name="system-guard-operator-api"),
    path("coach/cards/", views.coach_cards_page, name="coach-cards"),
    path("coach/staff/", views.staff_directory_page, name="staff-directory"),
    path("coach/staff/nuevo/", views.staff_member_create_page, name="staff-member-create"),
    path("coach/staff/<int:staff_id>/", views.staff_member_detail_page, name="staff-member-detail"),
    path("coach/staff/<int:staff_id>/photo/", views.staff_member_photo_file, name="staff-member-photo-file"),
    path("coach/staff/<int:staff_id>/license/", views.staff_member_license_file, name="staff-member-license-file"),
    path("coach/staff/<int:staff_id>/cert/", views.staff_member_cert_file, name="staff-member-cert-file"),
    path("coach/staff/<int:staff_id>/pdf/", views.staff_member_pdf, name="staff-member-pdf"),
    path("coach/rival/", views.coach_rival_page, name="coach-rival"),
    # Esta pagina (cards de rivales con la clasificacion: puesto, puntos, estadio,
    # informes y videos por rival) quedo INALCANZABLE al anadir mas arriba
    # "coach/rivales/" para las plantillas rivales importadas. Son dos cosas
    # distintas, asi que recupera su propia ruta; el nombre no cambia para no
    # romper los enlaces que ya existen.
    path("coach/rivales/clasificacion/", views.coach_rivals_page, name="coach-rivals"),
    path("coach/rivales/<int:rival_id>/", views.analysis_rival_profile_page, name="coach-rival-profile"),
    path("coach/plantilla/", views.coach_roster_page, name="coach-roster"),
    path("coach/plantilla/avatares/subir/", views.coach_upload_avatars, name="coach-upload-avatars"),
    # Completar de una vez los datos que necesita el avatar (ver football/avatar_data_views.py).
    path("coach/plantilla/avatares/datos/", avatar_data_views.coach_avatar_data_page, name="coach-avatar-data"),
    path("coach/plantilla/avatares/caracteristicas.xlsx", views.coach_avatar_characteristics_xlsx, name="coach-avatar-characteristics"),
    path("coach/plantilla/avatares/fotos.zip", views.coach_download_player_photos_zip, name="coach-download-photos-zip"),
    path("coach/plantilla/pdf/", views.coach_roster_pdf, name="coach-roster-pdf"),
    path("coach/plantilla/informe/", views.squad_status_report_page, name="coach-squad-report"),
    path("coach/plantilla/planificador/", views.squad_planner_page, name="squad-planner"),
    path("coach/microciclo/informe/", views.microcycle_report_page, name="coach-microcycle-report"),
    path("coach/entrenamiento/carga/", views.training_load_page, name="training-load"),
    path("coach/medico/", views.medical_center_page, name="medical-center"),
    path("coach/comparar/", views.player_compare_page, name="player-compare"),
    path("coach/bandeja/", views.coach_inbox_page, name="coach-inbox"),
    path("coach/desarrollo/", views.development_page, name="development"),
    path("coach/contratos/", views.contracts_page, name="contracts"),
    path("coach/tactica/roles/", views.tactics_roles_page, name="tactics-roles"),
    path("coach/equipo/", views.team_page, name="team-page"),
    path("coach/club/", views.club_page, name="club-page"),
    path("coach/partido/informe/", views.next_match_report_page, name="coach-next-match-report"),
    path("coach/plantilla/pizarra/guardar/", views.coach_pitch_board_save, name="coach-pitch-board-save"),
    path("coach/traspaso/buscar-destino/", views.coach_transfer_team_search, name="coach-transfer-team-search"),
    path("coach/torneos/", views.coach_tournaments_page, name="coach-tournaments"),
    path("coach/partidos/", views.coach_matches_page, name="coach-matches"),
    path("coach/calendario/mes/", views.coach_calendar_month_page, name="coach-calendar-month"),
    path("coach/partidos/sincronizar/", views.coach_matches_sync_universo, name="coach-matches-sync-universo"),
    path("coach/partidos/campos/", views.coach_matches_sync_venues, name="coach-matches-sync-venues"),
    path("coach/equipos/categorias/", views.coach_teams_fill_categories, name="coach-teams-fill-categories"),
    path("coach/equipos/plantilla-universo/", views.coach_team_import_squad, name="coach-team-import-squad"),
    path("coach/lesiones/", views.coach_injuries_page, name="coach-injuries"),
    path("coach/carga/", views.coach_load_page, name="coach-load"),
    path("coach/roles/entrenador/", views.coach_role_trainer_page, name="coach-role-trainer"),
    path("coach/roles/porteros/", views.coach_role_goalkeeper_page, name="coach-role-goalkeeper"),
    path("coach/roles/preparacion-fisica/", views.coach_role_fitness_page, name="coach-role-fitness"),
    path("coach/roles/abp/", views.coach_role_abp_page, name="coach-role-abp"),
    path("coach/system/guard/", views.system_guard_page, name="system-guard-page"),
    path("coach/abp/pizarra/", views.coach_abp_board_page, name="coach-abp-board"),
    path("coach/tactica/", views.coach_tactics_page, name="coach-tactics"),
    # Táctica · Planteamiento: el once frente al del rival, guardado por equipo.
    path("coach/tactica/planteamiento/", tactical_plan_views.tactical_plan_page, name="tactics-plan"),
    path("coach/tactica/planteamiento/guardar/", tactical_plan_views.tactical_plan_save, name="tactics-plan-save"),
    path("coach/tactica/planteamiento/borrar/", tactical_plan_views.tactical_plan_delete, name="tactics-plan-delete"),
    path("coach/tactica/planteamiento/rival/", tactical_plan_views.tactical_plan_rival_roster, name="tactics-plan-rival"),
    path("coach/tactica/planteamiento/aplicar/", tactical_plan_views.tactical_plan_apply, name="tactics-plan-apply"),
    path("coach/tactica/planteamiento/<int:plan_id>/campo/", tactical_plan_views.tactical_plan_board, name="tactics-plan-board"),
    path("coach/tactica/planteamiento/<int:plan_id>/imagen.png", tactical_plan_views.tactical_plan_image, name="tactics-plan-image"),
    path("coach/11-inicial/", views.initial_eleven_page, name="initial-eleven"),
    path("coach/sesiones/", views.sessions_page, name="sessions"),
    path("coach/sesiones/biblioteca/", views.session_library_page, name="session-library"),
    path("coach/sesiones/miniaturas/regenerar/", views.regenerate_task_previews_action, name="regenerate-task-previews"),
    path(
        "coach/sesiones/api/confirmed-players/",
        views.sessions_confirmed_players_api,
        name="sessions-confirmed-players-api",
    ),
    path("coach/sesiones/tareas/nueva/", views.sessions_task_create_page, name="sessions-task-create"),
    path("coach/sesiones/tareas/recursos/", views.sessions_task_library_page, name="sessions-task-library"),
    path("coach/sesiones/ia-trainer/", views.ai_trainer_page, name="ai-trainer"),
    path("coach/sesiones/modelo-juego/", views.coach_model_of_play_page, name="coach-model-of-play"),
    path("coach/sesiones/tareas/pdf-preview/", views.session_task_pdf_preview, name="sessions-task-pdf-preview"),
    path("coach/sesiones/tareas/video-import/", views.session_task_video_import_api, name="sessions-task-video-import"),
    path("coach/sesiones/tareas/<int:task_id>/editar/", views.sessions_task_edit_page, name="sessions-task-edit"),
    path("coach/sesiones/porteros/", views.sessions_goalkeeper_page, name="sessions-goalkeeper"),
    path(
        "coach/sesiones/porteros/tareas/nueva/",
        views.sessions_goalkeeper_task_create_page,
        name="sessions-goalkeeper-task-create",
    ),
    path(
        "coach/sesiones/porteros/tareas/recursos/",
        views.sessions_goalkeeper_task_library_page,
        name="sessions-goalkeeper-task-library",
    ),
    path(
        "coach/sesiones/porteros/tareas/<int:task_id>/editar/",
        views.sessions_goalkeeper_task_edit_page,
        name="sessions-goalkeeper-task-edit",
    ),
    path("coach/sesiones/preparacion-fisica/", views.sessions_fitness_page, name="sessions-fitness"),
    path(
        "coach/sesiones/preparacion-fisica/tareas/nueva/",
        views.sessions_fitness_task_create_page,
        name="sessions-fitness-task-create",
    ),
    path(
        "coach/sesiones/preparacion-fisica/tareas/recursos/",
        views.sessions_fitness_task_library_page,
        name="sessions-fitness-task-library",
    ),
    path(
        "coach/sesiones/preparacion-fisica/tareas/<int:task_id>/editar/",
        views.sessions_fitness_task_edit_page,
        name="sessions-fitness-task-edit",
    ),
    path("coach/sesiones/tarea/<int:task_id>/", views.session_task_detail_page, name="session-task-detail"),
    path(
        "coach/sesiones/tarea/<int:task_id>/bookmark/toggle/",
        views.toggle_session_task_bookmark,
        name="session-task-bookmark-toggle",
    ),
    path("coach/sesiones/tarea/<int:task_id>/related/", views.session_task_related_api, name="session-task-related"),
    path(
        "coach/sesiones/tarea/<int:task_id>/graphic/save/",
        views.save_session_task_graphic,
        name="session-task-graphic-save",
    ),
    path(
        "coach/sesiones/tarea/<int:task_id>/graphic/recreate/",
        views.recreate_session_task_graphic,
        name="session-task-graphic-recreate",
    ),
    path("coach/sesiones/tarea/<int:task_id>/archivo/", views.session_task_file, name="session-task-file"),
    path(
        "coach/sesiones/tarea/<int:task_id>/preview/", views.session_task_preview_file, name="session-task-preview-file"
    ),
    # Diagnostico de temporada: que temporada se usa para filtrar y a cual pertenece cada fila.
    path("coach/sesiones/diag-temporada/", season_diagnostics.season_debug_view, name="sessions-season-debug"),
    # Diagnostico de rendimiento de la pantalla de Entrenamiento: SQL vs Python y consultas caras.
    path("coach/sesiones/diag-perf/", season_diagnostics.sessions_perf_view, name="sessions-perf-debug"),
    # Comprueba que la copia ligera del layout clasifica igual que el campo completo.
    path("coach/sesiones/diag-layout-light/", season_diagnostics.task_meta_light_audit_view, name="sessions-layout-light-debug"),
    # Cuanto cuesta construir el contexto de cada formato (Club/UEFA) de una tarea.
    path("coach/sesiones/diag-formato/", season_diagnostics.task_format_cost_view, name="sessions-format-cost-debug"),
    # Radiografia de los microciclos de biblioteca antes de consolidarlos.
    path("coach/sesiones/diag-bibliotecas/", season_diagnostics.library_microcycles_audit_view, name="sessions-library-mc-debug"),
    # ¿El guion derivado dice lo mismo que los pasos guardados, y cuanto pesa?
    path("coach/sesiones/diag-guion/", season_diagnostics.task_script_audit_view, name="sessions-task-script-debug"),
    # La figura de una ficha, servida desde la tarea que ya la tiene guardada (ver
    # football/task_token_image.py): el reproductor pinta la MISMA chapa que la pizarra sin
    # duplicar 127 KB por jugador dentro del guion.
    path(
        "coach/sesiones/tarea/<int:task_id>/ficha/<str:uid>.png",
        task_token_image.session_task_token_image,
        name="session-task-token-image",
    ),
    # Pone al dia en lote las fotos HD de la biblioteca (?limit=, ?team=).
    path(
        "coach/sesiones/fotos-hd/",
        task_board_snapshot.board_snapshot_batch_view,
        name="session-tasks-board-hd-batch",
    ),
    # Estado (y disparo manual) de la FOTO HD de la pizarra: ?force=1 la vuelve a pedir.
    path(
        "coach/sesiones/tarea/<int:task_id>/foto-hd/",
        task_board_snapshot.board_snapshot_status_view,
        name="session-task-board-hd",
    ),
    # Sube una foto de la pizarra hecha fuera (el servidor no siempre puede con Chromium).
    path(
        "coach/sesiones/tarea/<int:task_id>/foto-hd/subir/",
        task_board_snapshot.board_snapshot_upload_view,
        name="session-task-board-hd-upload",
    ),
    path(
        "coach/sesiones/tarea/<int:task_id>/cover/", views.session_task_cover_file, name="session-task-cover-file"
    ),
    path("coach/sesiones/portadas/subir/", views.session_task_cover_upload, name="session-task-cover-upload"),
    path("coach/sesiones/portadas/escenas/", views.session_task_scenes_export, name="session-task-scenes-export"),
    path(
        "coach/sesiones/tarea/<int:task_id>/pdf-3d-embed/",
        views.session_task_pdf_3d_embed,
        name="session-task-pdf-3d-embed",
    ),
    path(
        "coach/sesiones/sesion-importada/<int:doc_id>/archivo/",
        views.imported_session_file,
        name="imported-session-file",
    ),
    path(
        "coach/sesiones/sesion-importada/<int:doc_id>/preview/",
        views.imported_session_preview_file,
        name="imported-session-preview-file",
    ),
    path("coach/sesiones/tarea/<int:task_id>/pdf/", views.session_task_pdf, name="session-task-pdf"),
    path("coach/sesiones/sesion/<int:session_id>/pdf/", session_pdf.session_plan_pdf, name="session-plan-pdf"),
    path("coach/sesiones/sesion/<int:session_id>/", views.training_session_detail_page, name="training-session-detail"),
    path(
        "coach/sesiones/microciclo/<int:microcycle_id>/presentacion/",
        views.microcycle_presentation_pdf,
        name="microcycle-presentation-pdf",
    ),
    path(
        "coach/sesiones/sesion/<int:session_id>/presentacion/",
        views.session_presentation_pdf,
        name="session-presentation-pdf",
    ),
    path(
        "coach/sesiones/tarea/<int:task_id>/canva/", views.session_task_canva_export, name="session-task-canva-export"
    ),
    path("coach/multas/", views.fines_page, name="fines"),
    path(
        "coach/analisis/informe/<int:report_id>/pdf/", views.analysis_rival_report_pdf, name="analysis-rival-report-pdf"
    ),
    path(
        "coach/analisis/informes/<int:report_id>/file/",
        views.analysis_match_report_file,
        name="analysis-match-report-file",
    ),
    path("coach/analisis/rival/<int:rival_id>/", views.analysis_rival_profile_page, name="analysis-rival-profile"),
    path("coach/analisis/", views.analysis_page, name="analysis"),
    path(
        "coach/analisis/video/informe/<int:report_id>/", views.analysis_video_report_page, name="analysis-video-report"
    ),
    path(
        "coach/analisis/video/informe/<int:report_id>/export/pptx/",
        views.analysis_video_report_export_pptx,
        name="analysis-video-report-export-pptx",
    ),
    path(
        "coach/analisis/video/informe/<int:report_id>/export/pdf/",
        views.analysis_video_report_export_pdf,
        name="analysis-video-report-export-pdf",
    ),
    path(
        "coach/analisis/video/informe/<int:report_id>/pptx/",
        views.analysis_video_report_pptx_file,
        name="analysis-video-report-pptx-file",
    ),
    path(
        "coach/analisis/video/informe/item/<int:item_id>/pizarra/",
        views.analysis_video_report_item_tactical_page,
        name="analysis-video-report-item-tactical",
    ),
    path(
        "coach/analisis/video/informe/item/<int:item_id>/pizarra/video/upload/",
        views.analysis_video_report_item_tactical_video_upload_api,
        name="analysis-video-report-item-tactical-video-upload-api",
    ),
    path("coach/analisis/inbox/", views.analysis_video_inbox_page, name="analysis-video-inbox"),
    path("coach/analisis/inbox/open/<int:item_id>/", views.analysis_video_inbox_open, name="analysis-video-inbox-open"),
    path("coach/estadisticas-manuales/", views.manual_player_stats_page, name="manual-player-stats"),
]
