# Generated by Django 4.2.27 on 2026-01-31 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=120)),
                ('result', models.CharField(blank=True, max_length=120)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('tercio', models.CharField(blank=True, max_length=120)),
                ('observation', models.CharField(blank=True, max_length=255)),
                ('system', models.CharField(blank=True, max_length=120)),
                ('source_file', models.CharField(max_length=200)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='football.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='football.player')),
            ],
            options={
                'verbose_name': 'Match Event',
                'verbose_name_plural': 'Match Events',
                'ordering': ['match', 'minute'],
            },
        ),
    ]
