# Generated by Django 4.2.27 on 2026-02-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_scrape_source_and_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('players', models.ManyToManyField(related_name='convocations', to='football.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='football.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
