# Generated by Django 4.2.27 on 2026-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_convocationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='preferente_url',
            field=models.URLField(blank=True, help_text='URL del equipo en LaPreferente'),
        ),
    ]
