# Generated by Django 4.2.27 on 2026-03-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_matchevent_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMicrocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Microciclo semanal', max_length=140)),
                ('objective', models.CharField(blank=True, max_length=200)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('closed', 'Cerrado')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microcycles', to='football.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microcycles', to='football.team')),
            ],
            options={
                'ordering': ['-week_start', '-id'],
                'unique_together': {('team', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=90)),
                ('intensity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('recovery', 'Recuperación'), ('matchday', 'Pre-partido')], default='medium', max_length=20)),
                ('focus', models.CharField(max_length=140)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('done', 'Realizada'), ('canceled', 'Cancelada')], default='planned', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('microcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='football.trainingmicrocycle')),
            ],
            options={
                'ordering': ['session_date', 'start_time', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('block', models.CharField(choices=[('activation', 'Activación'), ('main_1', 'Principal 1'), ('main_2', 'Principal 2'), ('set_pieces', 'ABP'), ('conditioning', 'Condicionante'), ('recovery', 'Vuelta calma'), ('video', 'Vídeo')], default='main_1', max_length=30)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('objective', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('done', 'Hecha'), ('skipped', 'No realizada')], default='planned', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='football.trainingsession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
