# Generated by Django 4.2.27 on 2026-03-21 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_sessiontask_uefab_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='player',
            name='injury',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='player',
            name='injury_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerPhysicalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('workload', models.CharField(blank=True, help_text='Ej. Fuerza + resistencia', max_length=120)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, help_text='Percepción del esfuerzo 1-10', null=True)),
                ('wellness', models.PositiveSmallIntegerField(blank=True, help_text='Bienestar 1-10', null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_metrics', to='football.player')),
            ],
            options={
                'ordering': ['-recorded_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('convocatoria', 'Convocatoria'), ('interna', 'Comunicación interna'), ('medica', 'Parte médico')], default='interna', max_length=20)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Fecha/hora objetivo de la comunicación', null=True)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_communications', to='football.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='football.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
