# Generated by Django 4.2.27 on 2026-03-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_player_birth_date_player_full_name_player_injury_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
