# Generated by Django 4.2.27 on 2026-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_player_height_cm_player_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInjuryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury', models.CharField(max_length=180)),
                ('injury_date', models.DateField()),
                ('return_date', models.DateField(blank=True, help_text='Fecha de alta médica/deportiva', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_records', to='football.player')),
            ],
            options={
                'ordering': ['-injury_date', '-id'],
            },
        ),
    ]
