# Generated by Django 4.2.27 on 2026-03-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_playerinjuryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injury_side',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='injury_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='player',
            name='injury_zone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='injury_side',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='injury_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='injury_zone',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
