# Generated by Django 4.2.27 on 2026-03-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0032_alter_matchevent_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='rivalvideo',
            name='assigned_players',
            field=models.ManyToManyField(blank=True, related_name='assigned_analysis_videos', to='football.player'),
        ),
        migrations.CreateModel(
            name='AnalystVideoFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rival_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_video_folders_as_rival', to='football.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_video_folders', to='football.team')),
            ],
            options={
                'ordering': ['name', '-created_at', '-id'],
                'unique_together': {('team', 'rival_team', 'name')},
            },
        ),
        migrations.AddField(
            model_name='rivalvideo',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='football.analystvideofolder'),
        ),
    ]
