# Generated by Django 4.2.27 on 2026-03-26 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0033_rivalvideo_assigned_players_analystvideofolder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserrole',
            name='role',
            field=models.CharField(choices=[('jugador', 'Jugador'), ('invitado', 'Invitado'), ('task_studio', 'Task Studio'), ('entrenador', 'Entrenador'), ('preparador_fisico', 'Preparador físico'), ('preparador_portero', 'Preparador portero'), ('analista', 'Analista'), ('administrador', 'Administrador')], default='jugador', max_length=32),
        ),
        migrations.CreateModel(
            name='TaskStudioTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('block', models.CharField(choices=[('activation', 'Activación'), ('main_1', 'Principal 1'), ('main_2', 'Principal 2'), ('set_pieces', 'ABP'), ('conditioning', 'Condicionante'), ('recovery', 'Vuelta calma'), ('video', 'Vídeo')], default='main_1', max_length=30)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('objective', models.CharField(blank=True, max_length=180)),
                ('coaching_points', models.TextField(blank=True)),
                ('confrontation_rules', models.TextField(blank=True)),
                ('tactical_layout', models.JSONField(blank=True, default=dict)),
                ('task_pdf', models.FileField(blank=True, null=True, upload_to='task-studio/task-pdfs/')),
                ('task_preview_image', models.ImageField(blank=True, null=True, upload_to='task-studio/task-previews/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_studio_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea Task Studio',
                'verbose_name_plural': 'Tareas Task Studio',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskStudioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('license_name', models.CharField(blank=True, max_length=120)),
                ('club_name', models.CharField(blank=True, max_length=140)),
                ('category_label', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('document_name', models.CharField(blank=True, max_length=140)),
                ('document_footer', models.CharField(blank=True, max_length=180)),
                ('signature', models.CharField(blank=True, max_length=140)),
                ('crest_image', models.ImageField(blank=True, null=True, upload_to='task-studio/crests/')),
                ('primary_color', models.CharField(default='#0f7a35', max_length=7)),
                ('secondary_color', models.CharField(default='#f8fafc', max_length=7)),
                ('accent_color', models.CharField(default='#102734', max_length=7)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_studio_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Task Studio',
                'verbose_name_plural': 'Perfiles Task Studio',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='TaskStudioRosterPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=60)),
                ('dominant_foot', models.CharField(blank=True, max_length=24)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='task-studio/roster/')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_studio_roster', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador plantilla Task Studio',
                'verbose_name_plural': 'Jugadores plantilla Task Studio',
                'ordering': ['number', 'name', 'id'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
