# Generated by Django 4.2.27 on 2026-03-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0036_workspace_enabled_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceCompetitionContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual', 'Manual / base local'), ('rfaf', 'RFAF'), ('universo_rfaf', 'Universo RFAF')], default='manual', max_length=32)),
                ('external_competition_key', models.CharField(blank=True, max_length=140)),
                ('external_group_key', models.CharField(blank=True, max_length=140)),
                ('external_team_key', models.CharField(blank=True, max_length=140)),
                ('external_team_name', models.CharField(blank=True, max_length=160)),
                ('is_auto_sync_enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Sincronizado'), ('error', 'Error')], default='pending', max_length=16)),
                ('sync_error', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_contexts', to='football.group')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_contexts', to='football.season')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_contexts', to='football.team')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competition_context', to='football.workspace')),
            ],
            options={
                'verbose_name': 'Contexto competitivo',
                'verbose_name_plural': 'Contextos competitivos',
                'ordering': ['workspace__name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCompetitionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standings_payload', models.JSONField(blank=True, default=list)),
                ('next_match_payload', models.JSONField(blank=True, default=dict)),
                ('schedule_payload', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='football.workspacecompetitioncontext')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competition_snapshot', to='football.workspace')),
            ],
            options={
                'verbose_name': 'Snapshot competitivo',
                'verbose_name_plural': 'Snapshots competitivos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
