# Generated by Django 4.2.27 on 2026-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0040_workspacemembership_module_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('task_pdf', 'PDF de tarea')], default='task_pdf', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enlace compartido',
                'verbose_name_plural': 'Enlaces compartidos',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
