# Generated by Django 4.2.27 on 2026-04-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0044_player_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='kind',
            field=models.CharField(choices=[('task_pdf', 'PDF de tarea'), ('convocation_pdf', 'PDF de convocatoria')], default='task_pdf', max_length=40),
        ),
        migrations.CreateModel(
            name='TeamRosterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('universo_rfaf', 'Universo RFAF'), ('lapreferente', 'La Preferente')], default='universo_rfaf', max_length=32)),
                ('roster_payload', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_snapshots', to='football.team')),
            ],
            options={
                'verbose_name': 'Snapshot plantilla (equipo)',
                'verbose_name_plural': 'Snapshots plantilla (equipos)',
                'ordering': ['-updated_at'],
                'unique_together': {('team', 'provider')},
            },
        ),
    ]
