# Generated by Django 4.2.27 on 2026-04-04 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0045_team_roster_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfGraphicAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('file', models.ImageField(upload_to='pdf-graphic-assets/')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('source_pdf_name', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_graphic_assets', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_graphic_assets', to='football.team')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pdfgraphicasset',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'sha256'), name='uniq_pdf_asset_team_sha256'),
        ),
        migrations.AddConstraint(
            model_name='pdfgraphicasset',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'sha256'), name='uniq_pdf_asset_owner_sha256'),
        ),
    ]
