# Generated by Django 4.2.27 on 2026-04-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0047_alter_sharelink_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='RivalConvocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('universo_rfaf', 'Universo RFAF'), ('lapreferente', 'La Preferente')], default='universo_rfaf', max_length=32)),
                ('convocation_data', models.JSONField(blank=True, default=list)),
                ('lineup_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_convocations', to='football.match')),
                ('rival_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_rival_convocations', to='football.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rival_convocations', to='football.team')),
            ],
            options={
                'verbose_name': 'Convocatoria rival',
                'verbose_name_plural': 'Convocatorias rival',
                'ordering': ['-updated_at', '-id'],
                'unique_together': {('team', 'match')},
            },
        ),
    ]
