# Generated by Django 4.2.27 on 2026-04-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0048_rivalconvocationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, help_text='Categoría del club (ej. Prebenjamín, Cadete, Senior). Solo se usa para equipos propios.', max_length=24),
        ),
        migrations.AddField(
            model_name='team',
            name='game_format',
            field=models.CharField(choices=[('f7', 'Fútbol 7'), ('f11', 'Fútbol 11')], default='f11', help_text='Formato de juego (afecta a convocatorias, 11/7 inicial y registro en vivo).', max_length=8),
        ),
        migrations.CreateModel(
            name='WorkspaceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_links', to='football.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football.workspace')),
            ],
            options={
                'verbose_name': 'Equipo del workspace',
                'verbose_name_plural': 'Equipos del workspace',
                'ordering': ['-is_default', 'id'],
                'unique_together': {('workspace', 'team')},
            },
        ),
    ]
