# Generated by Django 4.2.27 on 2026-04-06 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0050_bootstrap_workspaceteams'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceTeamAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_team_accesses', to='football.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_team_accesses', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_accesses', to='football.workspace')),
            ],
            options={
                'verbose_name': 'Acceso por categoría',
                'verbose_name_plural': 'Accesos por categorías',
                'ordering': ['workspace__name', 'user__username', '-is_default', 'id'],
                'unique_together': {('workspace', 'team', 'user')},
            },
        ),
    ]
