# Generated by Django 4.2.27 on 2026-04-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0056_workspace_trial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocationrecord',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_convocations', to='football.player'),
        ),
        migrations.AddField(
            model_name='convocationrecord',
            name='goalkeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goalkeeper_convocations', to='football.player'),
        ),
    ]
