# Generated by Django 4.2.27 on 2026-04-12 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0057_convocationrecord_captain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role_title', models.CharField(blank=True, help_text='Ej. Entrenador, Segundo, Fisio, Delegado', max_length=120)),
                ('certification_level', models.CharField(blank=True, help_text='Ej. UEFA B, CAFYD, TAFAD…', max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('photo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('federation_license', models.FileField(blank=True, help_text='PDF/JPG/PNG', null=True, upload_to='staff/licenses/')),
                ('license_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='football.team')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='football.workspace')),
            ],
            options={
                'verbose_name': 'Miembro del staff',
                'verbose_name_plural': 'Miembros del staff',
                'ordering': ['-is_active', 'role_title', 'name', '-updated_at', '-id'],
            },
        ),
    ]
