# Generated by Django 4.2.27 on 2026-04-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0059_staffmember_certification_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystMatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('opponent_name', models.CharField(blank=True, max_length=180)),
                ('match_date', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('document', models.FileField(upload_to='match-reports/')),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports', to='football.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_reports', to='football.team')),
            ],
            options={
                'verbose_name': 'Informe de partido (analista)',
                'verbose_name_plural': 'Informes de partido (analista)',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
