# Generated by Django 4.2.27 on 2026-04-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0061_staffmember_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('file', models.FileField(upload_to='assistant-knowledge/')),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_knowledge_documents', to='football.team')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assistantknowledgedocument',
            constraint=models.UniqueConstraint(fields=('team', 'sha256'), name='uniq_assistant_knowledge_team_sha256'),
        ),
    ]
