# Generated by Django 4.2.27 on 2026-04-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0063_system_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identificador estable (p.ej. ankle-sprain).', max_length=64, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('muscle', 'Muscular'), ('ligament', 'Ligamentosa'), ('tendon', 'Tendinosa'), ('bone', 'Ósea'), ('concussion', 'Conmoción'), ('other', 'Otra')], default='other', max_length=24)),
                ('region', models.CharField(choices=[('ankle', 'Tobillo'), ('knee', 'Rodilla'), ('hip_groin', 'Cadera / Aductores'), ('thigh', 'Muslo'), ('calf_achilles', 'Gemelo / Aquiles'), ('foot_toes', 'Pie / Dedos'), ('shoulder_clavicle', 'Hombro / Clavícula'), ('head', 'Cabeza'), ('back', 'Espalda'), ('other', 'Otra')], default='other', max_length=24)),
                ('typical_min_days', models.PositiveSmallIntegerField(default=0, help_text='Mínimo orientativo (días).')),
                ('typical_max_days', models.PositiveSmallIntegerField(default=0, help_text='Máximo orientativo (días).')),
                ('notes', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True, help_text='Fuente pública (opcional).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesión (catálogo)',
                'verbose_name_plural': 'Lesiones (catálogo)',
                'ordering': ['region', 'category', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='diagnosed_on',
            field=models.DateField(blank=True, help_text='Fecha de diagnóstico (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='estimated_return_date',
            field=models.DateField(blank=True, help_text='Alta estimada (orientativa).', null=True),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='rehab_started_on',
            field=models.DateField(blank=True, help_text='Inicio de readaptación/rehab (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='return_to_play_on',
            field=models.DateField(blank=True, help_text='Vuelta a competir (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='return_to_train_on',
            field=models.DateField(blank=True, help_text='Vuelta a entrenar (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='severity_grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Grado orientativo (1 leve · 2 moderada · 3 grave).', null=True),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='training_status',
            field=models.CharField(blank=True, help_text='Estado funcional: disponible · carga modificada · rehab · baja.', max_length=20),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='catalog_entry',
            field=models.ForeignKey(blank=True, help_text='Catálogo (opcional). Si se usa, permite métricas homogéneas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='football.injurycatalogentry'),
        ),
    ]
