# Generated by Django 4.2.27 on 2026-04-15

from django.db import migrations


def seed_injury_catalog(apps, schema_editor):
    InjuryCatalogEntry = apps.get_model('football', 'InjuryCatalogEntry')

    seeds = [
        {
            'code': 'ankle-sprain',
            'name': 'Esguince de tobillo',
            'category': 'ligament',
            'region': 'ankle',
            'typical_min_days': 7,
            'typical_max_days': 84,
            'notes': 'Rango orientativo (según grado).',
            'reference_url': 'https://www.nhsinform.scot/illnesses-and-conditions/muscle-bone-and-joints/leg-and-foot-problems-and-conditions/ankle-sprain/',
        },
        {
            'code': 'hamstring-strain',
            'name': 'Lesión isquios (distensión/rotura)',
            'category': 'muscle',
            'region': 'thigh',
            'typical_min_days': 7,
            'typical_max_days': 90,
            'notes': 'Rango orientativo (según grado y recidivas).',
            'reference_url': 'https://my.clevelandclinic.org/health/diseases/17039-hamstring-injury',
        },
        {
            'code': 'groin-strain',
            'name': 'Lesión aductores / ingle',
            'category': 'muscle',
            'region': 'hip_groin',
            'typical_min_days': 14,
            'typical_max_days': 84,
            'notes': 'Rango orientativo (según grado).',
            'reference_url': 'https://my.clevelandclinic.org/health/diseases/groin-strain',
        },
        {
            'code': 'mcl-injury',
            'name': 'Lesión LCM (MCL) rodilla',
            'category': 'ligament',
            'region': 'knee',
            'typical_min_days': 7,
            'typical_max_days': 56,
            'notes': 'Grado 1 suele 1–3 semanas; grados superiores pueden alargarse.',
            'reference_url': 'https://my.clevelandclinic.org/health/diseases/21979-mcl-tear',
        },
        {
            'code': 'meniscus-meniscectomy',
            'name': 'Menisco (meniscectomía parcial)',
            'category': 'other',
            'region': 'knee',
            'typical_min_days': 21,
            'typical_max_days': 42,
            'notes': 'Orientativo; depende de evolución y deporte.',
            'reference_url': 'https://orthoinfo.aaos.org/en/diseases--conditions/meniscus-tears/',
        },
        {
            'code': 'meniscus-repair',
            'name': 'Menisco (sutura/repair)',
            'category': 'other',
            'region': 'knee',
            'typical_min_days': 90,
            'typical_max_days': 180,
            'notes': 'Orientativo; rehab progresiva.',
            'reference_url': 'https://orthoinfo.aaos.org/en/diseases--conditions/meniscus-tears/',
        },
        {
            'code': 'acl-reconstruction',
            'name': 'LCA (reconstrucción)',
            'category': 'ligament',
            'region': 'knee',
            'typical_min_days': 270,
            'typical_max_days': 365,
            'notes': 'Vuelta a deporte según criterios/hitos. Orientativo.',
            'reference_url': 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12446172/',
        },
        {
            'code': 'achilles-rupture',
            'name': 'Rotura tendón de Aquiles',
            'category': 'tendon',
            'region': 'calf_achilles',
            'typical_min_days': 180,
            'typical_max_days': 365,
            'notes': 'Orientativo; puede alargarse.',
            'reference_url': 'https://orthoinfo.aaos.org/en/diseases--conditions/achilles-tendon-rupture-tear/',
        },
        {
            'code': 'metatarsal-fracture',
            'name': 'Fractura metatarsiano',
            'category': 'bone',
            'region': 'foot_toes',
            'typical_min_days': 42,
            'typical_max_days': 56,
            'notes': 'Orientativo si alineada y sin complicaciones.',
            'reference_url': 'https://medlineplus.gov/ency/patientinstructions/000571.htm',
        },
        {
            'code': 'clavicle-fracture',
            'name': 'Fractura de clavícula',
            'category': 'bone',
            'region': 'shoulder_clavicle',
            'typical_min_days': 42,
            'typical_max_days': 84,
            'notes': 'Rango orientativo; niños suelen menos.',
            'reference_url': 'https://www.hopkinsmedicine.org/health/conditions-and-diseases/clavicle-fractures',
        },
        {
            'code': 'toe-fracture',
            'name': 'Fractura dedo del pie',
            'category': 'bone',
            'region': 'foot_toes',
            'typical_min_days': 28,
            'typical_max_days': 56,
            'notes': 'Orientativo (4–6 semanas habitual; puede variar).',
            'reference_url': 'https://www.mayoclinic.org/diseases-conditions/broken-toe/symptoms-causes/syc-20370463',
        },
        {
            'code': 'stress-fracture',
            'name': 'Fractura por estrés',
            'category': 'bone',
            'region': 'other',
            'typical_min_days': 42,
            'typical_max_days': 84,
            'notes': 'Orientativo; según localización/carga.',
            'reference_url': 'https://my.clevelandclinic.org/health/diseases/15841-stress-fractures',
        },
        {
            'code': 'concussion',
            'name': 'Conmoción cerebral',
            'category': 'concussion',
            'region': 'head',
            'typical_min_days': 7,
            'typical_max_days': 28,
            'notes': 'Vuelta progresiva con supervisión. Orientativo.',
            'reference_url': 'https://www.cdc.gov/heads-up/guidelines/returning-to-sports.html',
        },
    ]

    for payload in seeds:
        InjuryCatalogEntry.objects.update_or_create(code=payload['code'], defaults=payload)


def unseed_injury_catalog(apps, schema_editor):
    InjuryCatalogEntry = apps.get_model('football', 'InjuryCatalogEntry')
    codes = [
        'ankle-sprain',
        'hamstring-strain',
        'groin-strain',
        'mcl-injury',
        'meniscus-meniscectomy',
        'meniscus-repair',
        'acl-reconstruction',
        'achilles-rupture',
        'metatarsal-fracture',
        'clavicle-fracture',
        'toe-fracture',
        'stress-fracture',
        'concussion',
    ]
    InjuryCatalogEntry.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0064_injurycatalogentry_playerinjuryrecord_diagnosed_on_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_injury_catalog, reverse_code=unseed_injury_catalog),
    ]

