# Generated by Django 4.2.27 on 2026-04-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0065_seed_injury_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='context',
            field=models.CharField(choices=[('league', 'Liga'), ('tournament', 'Torneo'), ('friendly', 'Amistoso')], default='league', help_text='Determina si el partido cuenta para la Liga (clasificación/próximo rival) o es Torneo/Amistoso.', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_name',
            field=models.CharField(blank=True, help_text='Nombre del torneo (solo si context=Torneo).', max_length=120),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_stage',
            field=models.CharField(blank=True, help_text='Fase/ronda del torneo (grupo, cuartos, semifinal, final...).', max_length=120),
        ),
    ]
