# Generated by Django 4.2.27 on 2026-04-17

from django.db import migrations


def seed_injury_catalog_more(apps, schema_editor):
    InjuryCatalogEntry = apps.get_model("football", "InjuryCatalogEntry")

    seeds = [
        {
            "code": "muscle-contusion",
            "name": "Contusión muscular",
            "category": "muscle",
            "region": "other",
            "typical_min_days": 3,
            "typical_max_days": 14,
            "notes": "Orientativo (según dolor/hematoma).",
            "reference_url": "https://www.nhs.uk/conditions/bruises/",
        },
        {
            "code": "quadriceps-strain",
            "name": "Lesión cuádriceps (distensión/rotura)",
            "category": "muscle",
            "region": "thigh",
            "typical_min_days": 7,
            "typical_max_days": 84,
            "notes": "Orientativo (según grado y recidiva).",
            "reference_url": "https://my.clevelandclinic.org/health/diseases/21206-quadriceps-tendonitis",
        },
        {
            "code": "calf-strain",
            "name": "Lesión gemelo/sóleo (distensión/rotura)",
            "category": "muscle",
            "region": "calf_achilles",
            "typical_min_days": 7,
            "typical_max_days": 84,
            "notes": "Orientativo (según grado).",
            "reference_url": "https://my.clevelandclinic.org/health/diseases/21834-calf-strain",
        },
        {
            "code": "hip-flexor-strain",
            "name": "Lesión flexor de cadera (psoas/recto anterior)",
            "category": "muscle",
            "region": "hip_groin",
            "typical_min_days": 7,
            "typical_max_days": 56,
            "notes": "Orientativo (según grado y carga).",
            "reference_url": "https://my.clevelandclinic.org/health/diseases/23400-hip-flexor-strain",
        },
        {
            "code": "adductor-tendinopathy",
            "name": "Tendinopatía aductores",
            "category": "tendon",
            "region": "hip_groin",
            "typical_min_days": 14,
            "typical_max_days": 90,
            "notes": "Suele requerir control de carga. Orientativo.",
            "reference_url": "https://www.nhs.uk/conditions/tendinopathy/",
        },
        {
            "code": "patellar-tendinopathy",
            "name": "Tendinopatía rotuliana (jumper's knee)",
            "category": "tendon",
            "region": "knee",
            "typical_min_days": 14,
            "typical_max_days": 120,
            "notes": "Orientativo; depende de cronicidad y carga.",
            "reference_url": "https://my.clevelandclinic.org/health/diseases/21962-patellar-tendinitis-jumpers-knee",
        },
        {
            "code": "achilles-tendinopathy",
            "name": "Tendinopatía aquilea",
            "category": "tendon",
            "region": "calf_achilles",
            "typical_min_days": 14,
            "typical_max_days": 180,
            "notes": "Orientativo; puede ser persistente si no se controla carga.",
            "reference_url": "https://my.clevelandclinic.org/health/diseases/21441-achilles-tendinitis",
        },
        {
            "code": "plantar-fasciitis",
            "name": "Fascitis plantar",
            "category": "other",
            "region": "foot_toes",
            "typical_min_days": 14,
            "typical_max_days": 180,
            "notes": "Orientativo; mejora con carga progresiva y calzado.",
            "reference_url": "https://www.mayoclinic.org/diseases-conditions/plantar-fasciitis/symptoms-causes/syc-20354846",
        },
        {
            "code": "shin-splints",
            "name": "Periostitis tibial (shin splints)",
            "category": "bone",
            "region": "other",
            "typical_min_days": 7,
            "typical_max_days": 56,
            "notes": "Orientativo; depende de carga/biomecánica.",
            "reference_url": "https://my.clevelandclinic.org/health/diseases/17467-shin-splints-medial-tibial-stress-syndrome",
        },
        {
            "code": "itb-syndrome",
            "name": "Síndrome cintilla iliotibial (ITB)",
            "category": "other",
            "region": "knee",
            "typical_min_days": 7,
            "typical_max_days": 56,
            "notes": "Orientativo; suele responder a ajustes de carga.",
            "reference_url": "https://my.clevelandclinic.org/health/diseases/21967-iliotibial-band-syndrome",
        },
        {
            "code": "knee-collateral-lcl",
            "name": "Lesión LCL rodilla",
            "category": "ligament",
            "region": "knee",
            "typical_min_days": 14,
            "typical_max_days": 84,
            "notes": "Orientativo (según grado).",
            "reference_url": "https://my.clevelandclinic.org/health/diseases/21507-lcl-tear",
        },
        {
            "code": "ankle-fracture",
            "name": "Fractura de tobillo",
            "category": "bone",
            "region": "ankle",
            "typical_min_days": 42,
            "typical_max_days": 120,
            "notes": "Orientativo; depende de tipo y tratamiento.",
            "reference_url": "https://orthoinfo.aaos.org/en/diseases--conditions/ankle-fractures-broken-ankle/",
        },
        {
            "code": "wrist-fracture",
            "name": "Fractura de muñeca",
            "category": "bone",
            "region": "other",
            "typical_min_days": 42,
            "typical_max_days": 84,
            "notes": "Orientativo (puede variar por tipo/edad).",
            "reference_url": "https://www.nhs.uk/conditions/broken-wrist/",
        },
        {
            "code": "shoulder-dislocation",
            "name": "Luxación de hombro",
            "category": "other",
            "region": "shoulder_clavicle",
            "typical_min_days": 21,
            "typical_max_days": 90,
            "notes": "Orientativo; riesgo de recidiva según perfil.",
            "reference_url": "https://www.nhs.uk/conditions/dislocated-shoulder/",
        },
        {
            "code": "low-back-pain",
            "name": "Dolor lumbar (lumbalgia)",
            "category": "other",
            "region": "back",
            "typical_min_days": 7,
            "typical_max_days": 56,
            "notes": "Orientativo; requiere individualizar.",
            "reference_url": "https://www.nhs.uk/conditions/back-pain/",
        },
        {
            "code": "groin-hernia",
            "name": "Pubalgia / hernia deportiva (dolor inguinal)",
            "category": "other",
            "region": "hip_groin",
            "typical_min_days": 21,
            "typical_max_days": 180,
            "notes": "Orientativo; a veces requiere manejo prolongado.",
            "reference_url": "https://my.clevelandclinic.org/health/diseases/23440-sports-hernia",
        },
        {
            "code": "osgood-schlatter",
            "name": "Osgood-Schlatter (crecimiento)",
            "category": "other",
            "region": "knee",
            "typical_min_days": 14,
            "typical_max_days": 180,
            "notes": "Frecuente en fútbol base; orientativo y dependiente de carga.",
            "reference_url": "https://www.nhs.uk/conditions/osgood-schlatter-disease/",
        },
    ]

    for payload in seeds:
        InjuryCatalogEntry.objects.update_or_create(code=payload["code"], defaults=payload)


def unseed_injury_catalog_more(apps, schema_editor):
    InjuryCatalogEntry = apps.get_model("football", "InjuryCatalogEntry")
    codes = [
        "muscle-contusion",
        "quadriceps-strain",
        "calf-strain",
        "hip-flexor-strain",
        "adductor-tendinopathy",
        "patellar-tendinopathy",
        "achilles-tendinopathy",
        "plantar-fasciitis",
        "shin-splints",
        "itb-syndrome",
        "knee-collateral-lcl",
        "ankle-fracture",
        "wrist-fracture",
        "shoulder-dislocation",
        "low-back-pain",
        "groin-hernia",
        "osgood-schlatter",
    ]
    InjuryCatalogEntry.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0066_match_context_match_tournament_name_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_injury_catalog_more, reverse_code=unseed_injury_catalog_more),
    ]

