# Generated by Django 4.2.27 on 2026-04-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0067_seed_injury_catalog_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalPlaybookClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('folder', models.CharField(blank=True, max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactical_playbook_clips', to='football.team')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['team', '-updated_at'], name='football_ta_team_id_c36af4_idx')],
            },
        ),
    ]
