# Generated by Django 4.2.27 on 2026-04-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0068_tacticalplaybookclip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalPlaybookClipFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='tacticalplaybookclip',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tacticalplaybookclip',
            name='version_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='tacticalplaybookclip',
            name='version_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='tacticalplaybookclip',
            index=models.Index(fields=['team', 'version_group', 'is_latest'], name='football_ta_team_id_58ea4c_idx'),
        ),
        migrations.AddField(
            model_name='tacticalplaybookclipfavorite',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_rows', to='football.tacticalplaybookclip'),
        ),
        migrations.AddField(
            model_name='tacticalplaybookclipfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactical_playbook_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tacticalplaybookclipfavorite',
            unique_together={('clip', 'user')},
        ),
    ]
