# Generated by Django 4.2.27 on 2026-04-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0069_playbook_pro'),
    ]

    def backfill_rivalvideo_team(apps, schema_editor):
        RivalVideo = apps.get_model('football', 'RivalVideo')
        AnalystVideoFolder = apps.get_model('football', 'AnalystVideoFolder')
        # Intenta resolver el equipo desde la carpeta cuando esté disponible.
        try:
            folders_by_id = {
                int(row['id']): int(row['team_id'])
                for row in AnalystVideoFolder.objects.exclude(team_id__isnull=True).values('id', 'team_id')
            }
        except Exception:
            folders_by_id = {}
        if not folders_by_id:
            return
        batch = []
        try:
            qs = RivalVideo.objects.filter(team_id__isnull=True).exclude(folder_id__isnull=True).values('id', 'folder_id')
            for row in qs.iterator():
                vid = int(row['id'])
                folder_id = int(row['folder_id'])
                team_id = folders_by_id.get(folder_id)
                if team_id:
                    batch.append((vid, team_id))
        except Exception:
            batch = []
        if not batch:
            return
        # Actualiza en lotes pequeños (DB portable).
        for vid, team_id in batch:
            try:
                RivalVideo.objects.filter(id=vid, team_id__isnull=True).update(team_id=team_id)
            except Exception:
                continue

    operations = [
        migrations.AddField(
            model_name='rivalvideo',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_videos', to='football.team'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='kind',
            field=models.CharField(choices=[('task_pdf', 'PDF de tarea'), ('convocation_pdf', 'PDF de convocatoria'), ('task_simulation', 'Simulación de tarea'), ('tactical_playbook_clip', 'Clip Playbook')], default='task_pdf', max_length=40),
        ),
        migrations.RunPython(backfill_rivalvideo_team, migrations.RunPython.noop),
        migrations.CreateModel(
            name='VideoTelestrationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_telestration_projects', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telestration_projects', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['team', '-updated_at'], name='football_vi_team_id_500fe3_idx'), models.Index(fields=['video', '-updated_at'], name='football_vi_video_i_132c9c_idx')],
            },
        ),
    ]
