# Generated by Django 4.2.27 on 2026-04-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0070_video_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ms', models.PositiveIntegerField(db_index=True, default=0)),
                ('kind', models.CharField(choices=[('tag', 'Tag'), ('note', 'Nota'), ('goal', 'Gol'), ('shot', 'Disparo'), ('press', 'Presión'), ('turnover', 'Pérdida'), ('abp', 'ABP')], default='tag', max_length=20)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_timeline_events', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['time_ms', 'id'],
                'indexes': [models.Index(fields=['team', 'video', 'time_ms'], name='football_vi_team_id_d9c3db_idx'), models.Index(fields=['video', 'time_ms'], name='football_vi_video_i_7362b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('collection', models.CharField(blank=True, help_text='Nombre de la colección/playlist (simple).', max_length=120)),
                ('in_ms', models.PositiveIntegerField(default=0)),
                ('out_ms', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('overlay', models.JSONField(blank=True, default=dict, help_text='Estado de la pizarra (fabric/canvas) para este clip.')),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_clips', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['team', 'video', '-updated_at'], name='football_vi_team_id_989ae1_idx'), models.Index(fields=['video', 'in_ms'], name='football_vi_video_i_b763e8_idx')],
            },
        ),
    ]
