# Generated by Django 4.2.27 on 2026-04-25 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0075_rename_football_imp_team_r_7fc531_idx_football_im_team_id_e33841_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontask',
            options={},
        ),
        migrations.CreateModel(
            name='SessionTaskBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='football.sessiontask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_task_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
