# Generated by Django 4.2.27 on 2026-04-25 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0076_session_task_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTaskCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(choices=[('traditional', 'Tradicionales'), ('interactive', 'Interactivas')], default='traditional', max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_collections', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_collections', to='football.team')),
            ],
            options={
                'ordering': ['name', 'id'],
                'unique_together': {('team', 'repository', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SessionTaskCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='football.sessiontaskcollection')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='football.sessiontask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('collection', 'task')},
            },
        ),
    ]
