# Generated by Django 4.2.27 on 2026-04-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0077_task_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoExportAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('file', models.FileField(upload_to='video-exports/')),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_assets', to='football.videoclip')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_export_assets', to='football.team')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_assets', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='football_vi_team_id_9222a2_idx'), models.Index(fields=['video', '-created_at'], name='football_vi_video_i_9310fc_idx'), models.Index(fields=['clip', '-created_at'], name='football_vi_clip_id_7ec6cb_idx')],
            },
        ),
    ]
