# Generated by Django 4.2.27 on 2026-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0078_videoexportasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='kind',
            field=models.CharField(choices=[('task_pdf', 'PDF de tarea'), ('convocation_pdf', 'PDF de convocatoria'), ('task_simulation', 'Simulación de tarea'), ('tactical_playbook_clip', 'Clip Playbook'), ('video_clip', 'Clip de vídeo'), ('video_export', 'Export de vídeo')], default='task_pdf', max_length=40),
        ),
    ]
