# Generated by Django 4.2.27 on 2026-04-25 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0079_alter_sharelink_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='kind',
            field=models.CharField(choices=[('task_pdf', 'PDF de tarea'), ('convocation_pdf', 'PDF de convocatoria'), ('task_simulation', 'Simulación de tarea'), ('tactical_playbook_clip', 'Clip Playbook'), ('video_clip', 'Clip de vídeo'), ('video_export', 'Export de vídeo'), ('video_playlist', 'Lista de clips (vídeo)')], default='task_pdf', max_length=40),
        ),
        migrations.CreateModel(
            name='VideoInboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('clip', 'Clip'), ('export', 'Export'), ('playlist', 'Playlist'), ('report', 'Informe')], default='clip', max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_inbox_sent', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_inbox', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_inbox_items', to='football.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_inbox_items', to='football.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', 'target_user', '-created_at'], name='football_vi_workspa_857f5f_idx'), models.Index(fields=['team', 'target_user', '-created_at'], name='football_vi_team_id_12a458_idx'), models.Index(fields=['target_user', 'is_read', '-created_at'], name='football_vi_target__c81df9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChunkedRivalVideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_name', models.CharField(blank=True, max_length=220)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('received_chunks', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunked_video_uploads', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_video_uploads', to='football.team')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='football_ch_team_id_e20c82_idx')],
            },
        ),
    ]
