# Generated by Django 4.2.27 on 2026-04-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0080_alter_sharelink_kind_videoinboxitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAiInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=12)),
                ('provider', models.CharField(blank=True, help_text='openai|heuristic|...', max_length=32)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ai_insights', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['team', 'video', '-updated_at'], name='football_vi_team_id_0f658b_idx'), models.Index(fields=['video', '-updated_at'], name='football_vi_video_i_89b5e4_idx')],
            },
        ),
    ]
