# Generated by Django 4.2.27 on 2026-04-25 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0081_videoaiinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='kind',
            field=models.CharField(choices=[('task_pdf', 'PDF de tarea'), ('convocation_pdf', 'PDF de convocatoria'), ('task_simulation', 'Simulación de tarea'), ('tactical_playbook_clip', 'Clip Playbook'), ('video_clip', 'Clip de vídeo'), ('video_export', 'Export de vídeo'), ('video_playlist', 'Lista de clips (vídeo)'), ('video_report', 'Informe PDF (vídeo)')], default='task_pdf', max_length=40),
        ),
        migrations.CreateModel(
            name='VideoReviewMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('clip', 'Clip'), ('event', 'Timeline')], default='clip', max_length=10)),
                ('object_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_done', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_review_marks', to='football.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_review_marks', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_marks', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['team', 'video', 'user', 'kind', 'object_id'], name='football_vi_team_id_442abb_idx'), models.Index(fields=['user', 'video', 'kind', '-updated_at'], name='football_vi_user_id_13e933_idx')],
                'unique_together': {('team', 'video', 'user', 'kind', 'object_id')},
            },
        ),
    ]
