# Generated by Django 4.2.27 on 2026-04-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0082_alter_sharelink_kind_videoreviewmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='football.workspace')),
            ],
            options={
                'verbose_name': 'Preferencia del workspace',
                'verbose_name_plural': 'Preferencias del workspace',
                'ordering': ['key', '-updated_at', '-id'],
                'unique_together': {('workspace', 'key')},
            },
        ),
    ]
