# Generated by Django 4.2.27 on 2026-04-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0083_workspacepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchVideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff_video_ms', models.PositiveIntegerField(default=0, help_text='Momento (ms) del vídeo donde empieza el partido.')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_markers', models.BooleanField(default=True, help_text='Crear marcador al registrar una acción.')),
                ('auto_clips', models.BooleanField(default=False, help_text='Crear clip IN/OUT al registrar una acción.')),
                ('clip_pre_ms', models.PositiveIntegerField(default=6000)),
                ('clip_post_ms', models.PositiveIntegerField(default=6000)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='football.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_video_links', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_links', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['team', 'match', 'is_active'], name='football_ma_team_id_da57f0_idx'), models.Index(fields=['video', 'is_active'], name='football_ma_video_i_a0d67b_idx')],
                'unique_together': {('team', 'match', 'video')},
            },
        ),
    ]
