# Generated by Django 4.2.27 on 2026-04-30 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0084_matchvideolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Llega tarde'), ('injured', 'Lesionado'), ('excused', 'Justificado')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_session_attendance_marks', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_session_attendance', to='football.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_marks', to='football.trainingsession')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'unique_together': {('session', 'player')},
            },
        ),
    ]
