# Generated by Django 4.2.27 on 2026-05-02 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0085_trainingsessionattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSessionTimelineSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('activation', 'Activación'), ('physical', 'Físico / Preventivo'), ('main', 'Tarea principal'), ('cooldown', 'Vuelta a la calma'), ('pause', 'Pausa'), ('other', 'Otro')], max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_session_timeline_segments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_segments', to='football.trainingsession')),
            ],
            options={
                'ordering': ['order', 'started_at', 'id'],
                'indexes': [models.Index(fields=['session', 'segment_type', 'order'], name='football_tr_session_5c7e19_idx'), models.Index(fields=['session', '-created_at'], name='football_tr_session_f2c284_idx')],
            },
        ),
    ]
