# Generated by Django 4.2.27 on 2026-05-03 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0088_remove_system_blueprint_dinamica1'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinboxitem',
            name='thread_key',
            field=models.CharField(blank=True, db_index=True, help_text='Clave compartida (entre destinatarios) para comentarios internos.', max_length=40),
        ),
        migrations.CreateModel(
            name='VideoInboxComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_key', models.CharField(db_index=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_inbox_comments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_inbox_comments', to='football.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_inbox_comments', to='football.workspace')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['workspace', 'team', 'thread_key', 'created_at'], name='football_vi_workspa_3f191a_idx')],
            },
        ),
    ]
