# Generated by Django 4.2.27 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0089_videoinboxitem_thread_key_videoinboxcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rivalvideo',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL de origen (p.ej. YouTube) si aplica.', max_length=600),
        ),
    ]

