# Generated by Django 4.2.27 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0091_alter_rivalvideo_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rivalvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rival-videos/'),
        ),
    ]

