# Generated by Django 4.2.27 on 2026-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0092_alter_rivalvideo_video_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfgraphicasset',
            name='embedded_data_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
