# Generated by GPT-5.2 on 2026-05-07

from django.db import migrations, models
from django.db.models import Count
import django.db.models.functions.text


def _dedupe_training_sessions(apps, schema_editor):
    """
    Si existen duplicados (microcycle+date+focus case-insensitive), mantenemos el más "útil"
    (más tareas; desempate por id más alto) y eliminamos el resto.

    Motivación: evitar que el AddConstraint falle en bases ya afectadas por doble-submit.
    """
    TrainingSession = apps.get_model('football', 'TrainingSession')

    dup_groups = (
        TrainingSession.objects
        .values('microcycle_id', 'session_date', focus_lower=django.db.models.functions.text.Lower('focus'))
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    for group in dup_groups.iterator():
        microcycle_id = group.get('microcycle_id')
        session_date = group.get('session_date')
        focus_lower = str(group.get('focus_lower') or '').strip()
        if not microcycle_id or not session_date or not focus_lower:
            continue
        candidates = (
            TrainingSession.objects
            .filter(microcycle_id=microcycle_id, session_date=session_date, focus__iexact=focus_lower)
            .annotate(task_count=Count('tasks'))
            .order_by('-task_count', '-id')
        )
        keep = candidates.first()
        if not keep:
            continue
        delete_qs = candidates.exclude(id=keep.id)
        if delete_qs.exists():
            delete_qs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0093_pdfgraphicasset_embedded_data_url'),
    ]

    operations = [
        migrations.RunPython(_dedupe_training_sessions, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(
                models.F('microcycle'),
                models.F('session_date'),
                django.db.models.functions.text.Lower('focus'),
                name='uniq_training_session_microcycle_date_focus_ci',
            ),
        ),
    ]

