# Generated by Django 4.2.27 on 2026-05-07 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('football', '0094_trainingsession_uniq_training_session_microcycle_date_focus_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_training_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='workflow_reason',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('proposed', 'Propuesta'), ('approved', 'Aprobada'), ('locked', 'Bloqueada')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='workflow_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='workflow_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_session_workflow_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrainingSessionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, help_text='RPE 1-10', null=True)),
                ('what_worked', models.TextField(blank=True, default='')),
                ('what_failed', models.TextField(blank=True, default='')),
                ('next_adjustment', models.TextField(blank=True, default='')),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_session_reviews', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='football.trainingsession')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('status', 'Estado/Workflow'), ('delete', 'Borrar')], default='update', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=240)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_content_type', 'target_object_id', '-created_at'], name='football_au_target__1a5485_idx'), models.Index(fields=['-created_at'], name='football_au_created_eb1e4c_idx')],
            },
        ),
    ]
