# Generated by Django 4.2.27 on 2026-05-08 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0095_trainingsession_locked_at_trainingsession_locked_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTrainerTokenWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('weight', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trainer_token_weights', to='football.team')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_trainer_token_weights', to='football.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'workspace', 'token'], name='football_ai_team_id_b34451_idx'), models.Index(fields=['team', '-updated_at'], name='football_ai_team_id_27c704_idx')],
                'unique_together': {('team', 'workspace', 'token')},
            },
        ),
        migrations.CreateModel(
            name='AiTrainerTaskIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(blank=True, max_length=32)),
                ('content', models.TextField(blank=True)),
                ('content_norm', models.TextField(blank=True)),
                ('tokens', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trainer_index', to='football.sessiontask')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trainer_task_index', to='football.team')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['team', 'repository', '-updated_at'], name='football_ai_team_id_4aa367_idx')],
            },
        ),
        migrations.CreateModel(
            name='AiTrainerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('generate', 'Generate proposals'), ('copy', 'Copy proposal'), ('save_task', 'Save proposal as task'), ('feedback', 'Feedback'), ('open_suggestion', 'Open suggested task')], max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trainer_events', to='football.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_trainer_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_trainer_events', to='football.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', 'event_type', '-created_at'], name='football_ai_team_id_8db208_idx'), models.Index(fields=['workspace', 'event_type', '-created_at'], name='football_ai_workspa_0f4dd0_idx'), models.Index(fields=['user', 'event_type', '-created_at'], name='football_ai_user_id_7ecaa6_idx')],
            },
        ),
    ]
