# Generated by Django 4.2.27 on 2026-05-08 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0096_ai_trainer_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTrainerDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('principles', 'Principios'), ('zones', 'Zonas'), ('phases', 'Fases'), ('figures', 'Figuras')], max_length=24)),
                ('entry_key', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('coaching_points', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_trainer_dictionary_entries', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trainer_dictionary_entries', to='football.team')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_trainer_dictionary_entries', to='football.workspace')),
            ],
            options={
                'ordering': ['section', 'entry_key', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['team', 'workspace', 'section', 'entry_key'], name='football_ai_team_id_be706d_idx'), models.Index(fields=['team', 'section', '-updated_at'], name='football_ai_team_id_8ae2f5_idx')],
                'unique_together': {('team', 'workspace', 'section', 'entry_key')},
            },
        ),
    ]
