# Generated by Django 4.2.27 on 2026-05-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0097_ai_trainer_dictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTaskBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField(db_index=True)),
                ('kind', models.CharField(db_index=True, default='session_task', max_length=40)),
                ('reason', models.CharField(blank=True, default='', max_length=80)),
                ('actor_username', models.CharField(blank=True, default='', max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_task_backups', to='football.team')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', 'kind', '-created_at'], name='football_se_team_id_0ea999_idx'), models.Index(fields=['team', 'task_id', '-created_at'], name='football_se_team_id_1db1a2_idx')],
            },
        ),
    ]
