# Generated by GPT-5.2 on 2026-05-08

from __future__ import annotations

from django.db import migrations, models


def _column_names(schema_editor, table_name: str) -> set[str]:
    conn = schema_editor.connection
    vendor = conn.vendor
    cursor = conn.cursor()
    if vendor == "sqlite":
        cursor.execute(f"PRAGMA table_info({table_name})")
        return {str(row[1]) for row in cursor.fetchall()}
    if vendor == "postgresql":
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = %s
            """,
            [table_name],
        )
        return {str(row[0]) for row in cursor.fetchall()}
    if vendor == "mysql":
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = %s
            """,
            [table_name],
        )
        return {str(row[0]) for row in cursor.fetchall()}
    return set()


def ensure_sessiontask_updated_at(apps, schema_editor):
    table = "football_sessiontask"
    cols = _column_names(schema_editor, table)
    if "updated_at" in cols:
        return

    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()
    # Añade columna con default para no romper inserts legacy.
    if vendor == "postgresql":
        cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN updated_at timestamp with time zone NULL')
        cursor.execute(f'UPDATE "{table}" SET updated_at = NOW() WHERE updated_at IS NULL')
        cursor.execute(f'ALTER TABLE "{table}" ALTER COLUMN updated_at SET NOT NULL')
        return
    if vendor == "sqlite":
        # SQLite: permite ADD COLUMN con NOT NULL solo si hay DEFAULT.
        cursor.execute(f"ALTER TABLE {table} ADD COLUMN updated_at datetime")
        cursor.execute(f"UPDATE {table} SET updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP)")
        return
    if vendor == "mysql":
        cursor.execute(f"ALTER TABLE {table} ADD COLUMN updated_at datetime NULL")
        cursor.execute(f"UPDATE {table} SET updated_at = NOW() WHERE updated_at IS NULL")
        cursor.execute(f"ALTER TABLE {table} MODIFY updated_at datetime NOT NULL")
        return


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0098_sessiontaskbackup"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_sessiontask_updated_at, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="sessiontask",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        )
    ]
