# Generated by GPT-5.2 on 2026-05-08

from __future__ import annotations

from django.db import migrations, models


def _column_names(schema_editor, table_name: str) -> set[str]:
    conn = schema_editor.connection
    vendor = conn.vendor
    cursor = conn.cursor()
    if vendor == "sqlite":
        cursor.execute(f"PRAGMA table_info({table_name})")
        return {str(row[1]) for row in cursor.fetchall()}
    if vendor in {"postgresql", "mysql"}:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = %s
            """,
            [table_name],
        )
        return {str(row[0]) for row in cursor.fetchall()}
    return set()


def ensure_sessiontask_workflow_columns(apps, schema_editor):
    table = "football_sessiontask"
    cols = _column_names(schema_editor, table)
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()

    def add_sqlite(col_sql: str, fill_sql: str | None = None):
        cursor.execute(f"ALTER TABLE {table} ADD COLUMN {col_sql}")
        if fill_sql:
            cursor.execute(fill_sql)

    if "workflow_is_latest" not in cols:
        if vendor == "sqlite":
            add_sqlite("workflow_is_latest bool", f"UPDATE {table} SET workflow_is_latest = COALESCE(workflow_is_latest, 1)")
        elif vendor == "postgresql":
            cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN workflow_is_latest boolean NOT NULL DEFAULT true')
        elif vendor == "mysql":
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN workflow_is_latest bool NOT NULL DEFAULT 1")

    if "workflow_status" not in cols:
        if vendor == "sqlite":
            add_sqlite("workflow_status varchar(12)", f"UPDATE {table} SET workflow_status = COALESCE(NULLIF(workflow_status,''), 'draft')")
        elif vendor == "postgresql":
            cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN workflow_status varchar(12) NOT NULL DEFAULT %s', ["draft"])
        elif vendor == "mysql":
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN workflow_status varchar(12) NOT NULL DEFAULT 'draft'")

    if "workflow_version_group" not in cols:
        if vendor == "sqlite":
            add_sqlite("workflow_version_group char(32)", f"UPDATE {table} SET workflow_version_group = COALESCE(workflow_version_group, '')")
        elif vendor == "postgresql":
            cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN workflow_version_group char(32) NOT NULL DEFAULT %s', [""])
        elif vendor == "mysql":
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN workflow_version_group char(32) NOT NULL DEFAULT ''")

    if "workflow_version_number" not in cols:
        if vendor == "sqlite":
            add_sqlite("workflow_version_number smallint unsigned", f"UPDATE {table} SET workflow_version_number = COALESCE(workflow_version_number, 1)")
        elif vendor == "postgresql":
            cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN workflow_version_number smallint NOT NULL DEFAULT 1')
        elif vendor == "mysql":
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN workflow_version_number smallint unsigned NOT NULL DEFAULT 1")


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0099_sessiontask_updated_at_model_sync"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_sessiontask_workflow_columns, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="sessiontask",
                    name="workflow_is_latest",
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name="sessiontask",
                    name="workflow_status",
                    field=models.CharField(default="draft", max_length=12),
                ),
                migrations.AddField(
                    model_name="sessiontask",
                    name="workflow_version_group",
                    field=models.CharField(blank=True, default="", max_length=32),
                ),
                migrations.AddField(
                    model_name="sessiontask",
                    name="workflow_version_number",
                    field=models.PositiveSmallIntegerField(default=1),
                ),
            ],
        )
    ]

