# Generated by GPT-5.2 on 2026-05-09

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0100_sessiontask_workflow_fields_model_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="rivalvideo",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Propietario cuando el vídeo está en biblioteca personal (sin team/folder).",
                null=True,
                on_delete=models.SET_NULL,
                related_name="personal_rival_videos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="videotelestrationproject",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="video_telestration_projects",
                to="football.team",
            ),
        ),
        migrations.AddField(
            model_name="videotelestrationproject",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Propietario cuando el proyecto está en biblioteca personal.",
                null=True,
                on_delete=models.SET_NULL,
                related_name="personal_video_telestration_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="videotimelineevent",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="video_timeline_events",
                to="football.team",
            ),
        ),
        migrations.AddField(
            model_name="videotimelineevent",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Propietario cuando el evento está en biblioteca personal.",
                null=True,
                on_delete=models.SET_NULL,
                related_name="personal_video_timeline_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="videoclip",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="video_clips",
                to="football.team",
            ),
        ),
        migrations.AddField(
            model_name="videoclip",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Propietario cuando el clip está en biblioteca personal.",
                null=True,
                on_delete=models.SET_NULL,
                related_name="personal_video_clips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

