# Generated by Django 4.2.27 on 2026-05-10 08:54

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('football', '0101_video_studio_personal_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoVoiceoverAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('file', models.FileField(upload_to='video-voiceovers/')),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_voiceovers', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiceovers', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['team', 'video', '-created_at'], name='football_vi_team_id_ef3bfd_idx'),
                    models.Index(fields=['video', '-created_at'], name='football_vi_video_i_7befd8_idx'),
                ],
            },
        ),
    ]
