# Generated by Django 4.2.27 on 2026-05-10 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0102_video_voiceovers'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStudioExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('playlist_mp4', 'Playlist MP4')], default='playlist_mp4', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En progreso'), ('done', 'Completado'), ('error', 'Error'), ('canceled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=220)),
                ('error', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_export_jobs', to=settings.AUTH_USER_MODEL)),
                ('export_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='football.videoexportasset')),
                ('share_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_export_jobs', to='football.sharelink')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_export_jobs', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', 'video', '-created_at'], name='football_vi_team_id_578eb5_idx'), models.Index(fields=['team', 'status', '-created_at'], name='football_vi_team_id_2ab7c4_idx'), models.Index(fields=['status', '-created_at'], name='football_vi_status_87321a_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoMusicAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('file', models.FileField(upload_to='video-music/')),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_music_assets', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_assets', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', 'video', '-created_at'], name='football_vi_team_id_39ed1a_idx'), models.Index(fields=['video', '-created_at'], name='football_vi_video_i_1d5e93_idx')],
            },
        ),
    ]
