# Generated by Django 4.2.27 on 2026-05-11 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0104_rivalvideo_trim_enabled_rivalvideo_trim_in_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ej. 2025/2026', max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_seasons', to='football.workspace')),
            ],
            options={
                'verbose_name': 'Temporada (club)',
                'verbose_name_plural': 'Temporadas (club)',
                'ordering': ['-is_active', '-start_date', '-id'],
                'unique_together': {('workspace', 'label')},
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='active_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_workspaces', to='football.workspaceseason'),
        ),
        migrations.CreateModel(
            name='WorkspaceSeasonPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(db_index=True, default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_player_confirmations', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_memberships', to='football.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_players', to='football.workspaceseason')),
            ],
            options={
                'verbose_name': 'Jugador de temporada (club)',
                'verbose_name_plural': 'Jugadores de temporada (club)',
                'ordering': ['-is_confirmed', 'player__name', 'id'],
                'unique_together': {('season', 'player')},
            },
        ),
    ]
