# Generated by Django 4.2.27 on 2026-05-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0106_videoclip_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystvideofolder',
            name='base_video',
            field=models.ForeignKey(blank=True, help_text='Vídeo base de la carpeta (partido completo) para recortar clips.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_for_folders', to='football.rivalvideo'),
        ),
    ]
