# Generated by Django 4.2.27 on 2026-05-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0107_analystvideofolder_base_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='rivalvideo',
            name='is_base',
            field=models.BooleanField(default=False, help_text='Marca el vídeo como “base” (partido completo) para que aparezca fijado arriba y sea fácil seguir recortando.'),
        ),
    ]
