# Generated by Django 4.2.27 on 2026-05-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0108_rivalvideo_is_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystvideofolder',
            name='is_visible_to_players',
            field=models.BooleanField(default=False, help_text='Si está activo, la carpeta (y sus vídeos) se muestra en el espacio de Jugadores del equipo.'),
        ),
    ]

