# Generated by Django 4.2.27 on 2026-05-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0109_analystvideofolder_is_visible_to_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisVideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('pptx_file', models.FileField(blank=True, null=True, upload_to='analysis-reports/pptx/')),
                ('pptx_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='football.analystvideofolder')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_video_reports', to='football.team')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisVideoReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_report_items', to='football.videoclip')),
                ('export_asset', models.ForeignKey(blank=True, help_text='Export MP4 a incrustar en el PPTX. Si está vacío, se usa el último export del clip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_report_items', to='football.videoexportasset')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='football.analysisvideoreport')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisVideoReportItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='analysis-reports/images/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='football.analysisvideoreportitem')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['item', 'position'], name='football_an_item_id_862989_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='analysisvideoreportitem',
            index=models.Index(fields=['report', 'position'], name='football_an_report__b9d539_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisvideoreportitem',
            index=models.Index(fields=['clip', '-updated_at'], name='football_an_clip_id_dc3103_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisvideoreport',
            index=models.Index(fields=['team', 'folder', '-updated_at'], name='football_an_team_id_ce8df1_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisvideoreport',
            index=models.Index(fields=['folder', '-updated_at'], name='football_an_folder__933385_idx'),
        ),
    ]
