# Generated by Django 4.2.27 on 2026-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0110_analysisvideoreport_analysisvideoreportitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisvideoreportitem',
            name='tactical_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysisvideoreportitem',
            name='tactical_preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='analysis-reports/tactics/'),
        ),
    ]
