# Generated by Django 4.2.27 on 2026-05-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0111_analysisvideoreportitem_tactical_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisvideoreportitem',
            name='tactical_video',
            field=models.FileField(blank=True, null=True, upload_to='analysis-reports/tactics/video/'),
        ),
    ]
