# Generated by Django 4.2.27 on 2026-05-17 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0113_alter_group_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(blank=True, default='', max_length=80)),
                ('scope', models.CharField(blank=True, default='', max_length=24)),
                ('tournament_name', models.CharField(blank=True, default='', max_length=120)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-10 (opcional)', null=True)),
                ('technical_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-10 (opcional)', null=True)),
                ('tactical_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-10 (opcional)', null=True)),
                ('physical_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-10 (opcional)', null=True)),
                ('mental_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-10 (opcional)', null=True)),
                ('social_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-10 (opcional)', null=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('objectives_next', models.TextField(blank=True)),
                ('coach_comments', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_player_season_reports', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_reports', to='football.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_season_reports', to='football.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_player_season_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe de temporada (jugador)',
                'verbose_name_plural': 'Informes de temporada (jugadores)',
                'ordering': ['-updated_at', '-id'],
                'unique_together': {('team', 'player', 'season_label', 'scope', 'tournament_name')},
            },
        ),
    ]
