# Generated by Django 4.2.27 on 2026-05-17 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0115_playerseasonreport_ring_kpis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_override', models.CharField(blank=True, max_length=220)),
                ('is_required', models.BooleanField(default=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estable (auto).', unique=True)),
                ('title', models.CharField(max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('min_category', models.CharField(choices=[('baby', 'Baby'), ('prebenjamin', 'Prebenjamín'), ('benjamin', 'Benjamín'), ('alevin', 'Alevín'), ('infantil', 'Infantil'), ('cadete', 'Cadete'), ('juvenil', 'Juvenil'), ('senior', 'Senior')], default='baby', max_length=24)),
                ('max_category', models.CharField(choices=[('baby', 'Baby'), ('prebenjamin', 'Prebenjamín'), ('benjamin', 'Benjamín'), ('alevin', 'Alevín'), ('infantil', 'Infantil'), ('cadete', 'Cadete'), ('juvenil', 'Juvenil'), ('senior', 'Senior')], default='senior', max_length=24)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademyLessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('step_type', models.CharField(choices=[('text', 'Texto'), ('video', 'Vídeo'), ('quiz', 'Quiz'), ('replay2d', 'Replay 2D'), ('replay3d', 'Replay 3D'), ('task', 'Reto de campo')], default='text', max_length=16)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Datos extra (p.ej. JSON replay2d, config 3D, etc.).')),
                ('is_required', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='football.academylesson')),
            ],
            options={
                'ordering': ['lesson_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AcademyMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('video', 'Vídeo'), ('image', 'Imagen')], default='video', max_length=16)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('file', models.FileField(blank=True, null=True, upload_to='academy/assets/')),
                ('source_url', models.URLField(blank=True, help_text='URL externa (YouTube/Vimeo/CDN) si aplica.', max_length=600)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademyQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=320)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='football.academylessonstep')),
            ],
            options={
                'ordering': ['step_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AcademyQuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=240)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, max_length=320)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='football.academyquizquestion')),
            ],
            options={
                'ordering': ['question_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AcademyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En progreso'), ('completed', 'Completado')], db_index=True, default='not_started', max_length=16)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Registro simple de respuestas: {question_id: option_id}')),
                ('answer_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_rows', to='football.academyassignment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='football.academylesson')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_progress_rows', to='football.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_progress_rows', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_progress_rows', to='football.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='academylessonstep',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='football.academymediaasset'),
        ),
        migrations.AddIndex(
            model_name='academylesson',
            index=models.Index(fields=['is_published', '-updated_at'], name='football_ac_is_publ_f6ef82_idx'),
        ),
        migrations.AddField(
            model_name='academyassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academyassignment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='football.academylesson'),
        ),
        migrations.AddField(
            model_name='academyassignment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_assignments', to='football.team'),
        ),
        migrations.AddField(
            model_name='academyassignment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_assignments', to='football.workspace'),
        ),
        migrations.AddIndex(
            model_name='academyquizquestion',
            index=models.Index(fields=['step', 'order'], name='football_ac_step_id_708db1_idx'),
        ),
        migrations.AddIndex(
            model_name='academyquizoption',
            index=models.Index(fields=['question', 'order'], name='football_ac_questio_9e9148_idx'),
        ),
        migrations.AddIndex(
            model_name='academyprogress',
            index=models.Index(fields=['workspace', 'user', 'status'], name='football_ac_workspa_ad6fea_idx'),
        ),
        migrations.AddIndex(
            model_name='academyprogress',
            index=models.Index(fields=['workspace', 'lesson', 'status'], name='football_ac_workspa_e137fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='academyprogress',
            constraint=models.UniqueConstraint(fields=('workspace', 'user', 'lesson'), name='uniq_academy_progress_workspace_user_lesson'),
        ),
        migrations.AddIndex(
            model_name='academylessonstep',
            index=models.Index(fields=['lesson', 'order'], name='football_ac_lesson__86bb54_idx'),
        ),
        migrations.AddIndex(
            model_name='academyassignment',
            index=models.Index(fields=['workspace', 'is_active', '-created_at'], name='football_ac_workspa_05aacc_idx'),
        ),
    ]
