# Generated by Django 4.2.27 on 2026-05-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0116_academyassignment_academylesson_academylessonstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSeasonPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('recruitment', 'Captación'), ('preseason', 'Pretemporada'), ('regular', 'Temporada regular'), ('playoffs', 'Playoff / eliminatorias'), ('offseason', 'Fuera de temporada'), ('custom', 'Personalizada')], db_index=True, default='custom', max_length=24)),
                ('label', models.CharField(help_text='Nombre visible. Ej: Captación, Pretemporada…', max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='football.workspaceseason')),
            ],
            options={
                'verbose_name': 'Fase de temporada (club)',
                'verbose_name_plural': 'Fases de temporada (club)',
                'ordering': ['season_id', 'sort_order', 'start_date', 'id'],
            },
        ),
    ]
