# Generated by Django 4.2.27 on 2026-05-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0118_playerseasonreport_manual_overrides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchVideoLink',
        ),
    ]
