# Generated by Django 4.2.27 on 2026-05-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0119_delete_matchvideolink'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='convocationrecord',
            index=models.Index(fields=['team', 'match'], name='conv_team_match_idx'),
        ),
        migrations.AddIndex(
            model_name='convocationrecord',
            index=models.Index(fields=['team', 'is_current', 'created_at'], name='conv_team_curr_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'player'], name='me_match_player_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'system', 'source_file', 'created_at'], name='me_m_sys_src_ca_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatistic',
            index=models.Index(fields=['context', 'match'], name='pstat_ctx_match_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstatistic',
            index=models.Index(fields=['player', 'match', 'context'], name='pstat_p_m_ctx_idx'),
        ),
    ]
