# Generated by Django 4.2.27 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0120_perf_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["home_team", "date"], name="match_home_date_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["away_team", "date"], name="match_away_date_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["season", "date"], name="match_season_date_idx"),
        ),
    ]

