# Generated by Django 4.2.27 on 2026-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0121_match_query_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceseasonplayer',
            name='questionnaire',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workspaceseasonplayer',
            name='questionnaire_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceseasonplayer',
            name='questionnaire_v',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
