# Generated by Django 4.2.27 on 2026-05-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0122_season_player_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedrivalvideoupload',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunked_video_uploads', to='football.team'),
        ),
        migrations.AddIndex(
            model_name='chunkedrivalvideoupload',
            index=models.Index(fields=['created_by_user', '-created_at'], name='chu_user_created_idx'),
        ),
    ]
