# Generated by Django 4.2.27 on 2026-05-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0122_season_player_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontask',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskstudiotask',
            name='objective',
            field=models.TextField(blank=True),
        ),
    ]
