# Generated by Django 4.2.27 on 2026-05-31 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0129_workspace_season_team_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisvideoreport',
            name='club_season',
            field=models.ForeignKey(blank=True, help_text='Temporada interna del club para informes de análisis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_video_reports', to='football.workspaceseason'),
        ),
        migrations.AddField(
            model_name='match',
            name='club_season',
            field=models.ForeignKey(blank=True, help_text='Temporada interna del club para histórico y filtrado multitemporada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='football.workspaceseason'),
        ),
        migrations.AddField(
            model_name='rivalanalysisreport',
            name='club_season',
            field=models.ForeignKey(blank=True, help_text='Temporada interna del club para informes de rival.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_analysis_reports', to='football.workspaceseason'),
        ),
        migrations.AddField(
            model_name='rivalvideo',
            name='club_season',
            field=models.ForeignKey(blank=True, help_text='Temporada interna del club para biblioteca de análisis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_videos', to='football.workspaceseason'),
        ),
        migrations.AddField(
            model_name='sessiontask',
            name='club_season',
            field=models.ForeignKey(blank=True, help_text='Temporada interna del club heredada de la sesión o asignada por backfill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_tasks', to='football.workspaceseason'),
        ),
        migrations.AddField(
            model_name='tacticalplaybookclip',
            name='club_season',
            field=models.ForeignKey(blank=True, help_text='Temporada interna del club para plantillas y clips tácticos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tactical_playbook_clips', to='football.workspaceseason'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='club_season',
            field=models.ForeignKey(blank=True, help_text='Temporada interna del club para histórico y planificación por año.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='football.workspaceseason'),
        ),
        migrations.AddIndex(
            model_name='analysisvideoreport',
            index=models.Index(fields=['club_season', '-updated_at'], name='avr_club_season_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['club_season', 'date'], name='match_club_season_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tacticalplaybookclip',
            index=models.Index(fields=['club_season', '-updated_at'], name='clip_club_season_updated_idx'),
        ),
    ]
