# Generated by Django 4.2.27 on 2026-05-31 10:55

from django.db import migrations, models
import django.db.models.deletion


def backfill_workspace_players(apps, schema_editor):
    WorkspacePlayer = apps.get_model('football', 'WorkspacePlayer')
    WorkspaceTeam = apps.get_model('football', 'WorkspaceTeam')
    WorkspaceSeasonPlayer = apps.get_model('football', 'WorkspaceSeasonPlayer')
    Player = apps.get_model('football', 'Player')

    team_workspace = {}
    for link in WorkspaceTeam.objects.select_related('workspace', 'team').all().only('workspace_id', 'team_id'):
        if link.team_id and link.workspace_id:
            team_workspace.setdefault(int(link.team_id), int(link.workspace_id))

    for player in Player.objects.all().only('id', 'team_id', 'is_active'):
        workspace_id = team_workspace.get(int(player.team_id or 0))
        if not workspace_id:
            continue
        WorkspacePlayer.objects.get_or_create(
            workspace_id=workspace_id,
            player_id=player.id,
            defaults={
                'current_team_id': player.team_id,
                'is_active': bool(player.is_active),
            },
        )

    for membership in WorkspaceSeasonPlayer.objects.select_related('player', 'season').filter(team__isnull=True):
        player = getattr(membership, 'player', None)
        season = getattr(membership, 'season', None)
        player_team_id = int(getattr(player, 'team_id', 0) or 0)
        workspace_id = int(getattr(season, 'workspace_id', 0) or 0)
        if not player_team_id or not workspace_id:
            continue
        if team_workspace.get(player_team_id) != workspace_id:
            continue
        membership.team_id = player_team_id
        membership.save(update_fields=['team'])


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0130_analysisvideoreport_club_season_match_club_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspacePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jugador del workspace',
                'verbose_name_plural': 'Jugadores del workspace',
                'ordering': ['-is_active', 'player__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='workspaceseasonplayer',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Categoría/equipo del club en la que participa este jugador durante la temporada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_player_memberships', to='football.team'),
        ),
        migrations.AddIndex(
            model_name='workspaceseasonplayer',
            index=models.Index(fields=['season', 'team', 'status'], name='wsp_season_team_status_idx'),
        ),
        migrations.AddField(
            model_name='workspaceplayer',
            name='current_team',
            field=models.ForeignKey(blank=True, help_text='Categoría/equipo actual sugerido dentro del club.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_player_current_links', to='football.team'),
        ),
        migrations.AddField(
            model_name='workspaceplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_links', to='football.player'),
        ),
        migrations.AddField(
            model_name='workspaceplayer',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.workspace'),
        ),
        migrations.AddIndex(
            model_name='workspaceplayer',
            index=models.Index(fields=['workspace', 'is_active'], name='wp_workspace_active_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceplayer',
            index=models.Index(fields=['current_team', 'is_active'], name='wp_team_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceplayer',
            unique_together={('workspace', 'player')},
        ),
        migrations.RunPython(backfill_workspace_players, migrations.RunPython.noop),
    ]
