# Generated by Django 4.2.27 on 2026-06-02 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0133_player_dominant_foot_player_origin_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('initial', 'Inicial'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('final', 'Final'), ('post_round', 'Post-jornada')], default='monthly', max_length=24)),
                ('evaluated_on', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('closed', 'Cerrada')], default='draft', max_length=16)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('evaluated_position', models.CharField(blank=True, max_length=60)),
                ('recommended_position', models.CharField(blank=True, max_length=60)),
                ('technical_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tactical_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('physical_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('mental_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('social_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('objectives_next', models.TextField(blank=True)),
                ('coach_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_evaluations', to='football.workspaceseason')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_player_evaluations', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='football.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_evaluations', to='football.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_player_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación de jugador',
                'verbose_name_plural': 'Evaluaciones de jugadores',
                'ordering': ['-evaluated_on', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['player', '-evaluated_on'], name='football_pl_player__c287da_idx'), models.Index(fields=['team', 'club_season', '-evaluated_on'], name='football_pl_team_id_989035_idx'), models.Index(fields=['status', '-evaluated_on'], name='football_pl_status_38f652_idx')],
            },
        ),
    ]
