# Generated by Django 4.2.27 on 2026-06-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0134_playerevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerevaluation',
            name='agility_505_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='availability_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Disponibilidad/asistencia 1-10.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='cmj_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salto CMJ en cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='copenhagen_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='evidence_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='growth_velocity_cm_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Velocidad de crecimiento cm/año.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='maturation_status',
            field=models.CharField(blank=True, choices=[('', 'Sin definir'), ('pre_phv', 'Pre-PHV'), ('circa_phv', 'Circa-PHV'), ('post_phv', 'Post-PHV')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='maturity_offset_years',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Años estimados respecto al PHV.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='objective_performance_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Síntesis objetiva 1-10 basada en KPIs/datos disponibles.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='session_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duración de sesión/partido en minutos.', null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='session_rpe',
            field=models.PositiveSmallIntegerField(blank=True, help_text='RPE sesión 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='single_leg_control_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Control monopodal 1-10.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='sprint_10m_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='sprint_20m_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='sprint_5m_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='wellness_fatigue',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Fatiga percibida 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='wellness_motivation',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Motivación 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='wellness_sleep',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sueño/descanso 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='wellness_soreness',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dolor muscular 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='wellness_stress',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estrés percibido 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='yo_yo_ir1_m',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Yo-Yo IR1 en metros.', null=True),
        ),
    ]
