# Generated by Django 4.2.27 on 2026-06-13 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0135_playerevaluation_agility_505_s_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAiTrackJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reid', 'ReID')], default='reid', max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En progreso'), ('done', 'Completado'), ('error', 'Error'), ('canceled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=220)),
                ('error', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_track_jobs', to='football.videoclip')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_ai_track_jobs', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ai_track_jobs', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_track_jobs', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', 'video', '-created_at'], name='football_vi_team_id_f98e4b_idx'), models.Index(fields=['team', 'status', '-created_at'], name='football_vi_team_id_2b47db_idx'), models.Index(fields=['status', '-created_at'], name='football_vi_status_8c45bf_idx')],
            },
        ),
    ]
