# Generated by Django 4.2.27 on 2026-06-13 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0136_video_ai_track_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoaitrackjob',
            name='action',
            field=models.CharField(choices=[('reid', 'ReID'), ('batch', 'Batch'), ('train', 'Entrenamiento')], default='reid', max_length=24),
        ),
        migrations.CreateModel(
            name='VideoAiCorrectionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_uid', models.CharField(blank=True, max_length=100)),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('x_rel', models.FloatField(default=0)),
                ('y_rel', models.FloatField(default=0)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_correction_examples', to='football.videoclip')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_ai_correction_examples', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ai_correction_examples', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_correction_examples', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', 'video', '-created_at'], name='football_vi_team_id_2fad1a_idx'), models.Index(fields=['video', 'marker_uid', 'time_ms'], name='football_vi_video_i_e3b4c5_idx'), models.Index(fields=['team', '-created_at'], name='football_vi_team_id_bf29e9_idx')],
            },
        ),
    ]
