# Generated by Django 4.2.27 on 2026-06-13 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0137_video_ai_pro_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoaitrackjob',
            name='action',
            field=models.CharField(choices=[('reid', 'ReID'), ('batch', 'Batch'), ('train', 'Entrenamiento'), ('detect_actions', 'Detección de acciones'), ('train_actions', 'Entrenamiento de acciones')], default='reid', max_length=24),
        ),
        migrations.CreateModel(
            name='VideoAiActionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(db_index=True, max_length=80)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_positive', models.BooleanField(default=True)),
                ('start_ms', models.PositiveIntegerField(default=0)),
                ('end_ms', models.PositiveIntegerField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_action_examples', to='football.videoclip')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_ai_action_examples', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ai_action_examples', to='football.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_examples', to='football.rivalvideo')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', 'video', '-created_at'], name='football_vi_team_id_73d21d_idx'), models.Index(fields=['team', 'action_key', '-created_at'], name='football_vi_team_id_8a2eaa_idx'), models.Index(fields=['video', 'start_ms', 'end_ms'], name='football_vi_video_i_489794_idx')],
            },
        ),
    ]
