# Generated by Django 4.2.27 on 2026-06-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0138_video_ai_action_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAiKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=80)),
                ('concept_key', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=60)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_ai_knowledge_entries', to='football.team')),
            ],
            options={
                'ordering': ['category', 'title', 'id'],
                'indexes': [models.Index(fields=['team', 'category', 'is_active'], name='football_vi_team_id_59ffac_idx'), models.Index(fields=['team', 'concept_key'], name='football_vi_team_id_2d51bb_idx'), models.Index(fields=['source_key', 'category'], name='football_vi_source__c93d52_idx')],
                'unique_together': {('team', 'concept_key')},
            },
        ),
    ]
