# Generated by Django 4.2.27 on 2026-07-21 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0144_serviceaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seguimiento de scouting',
                'verbose_name_plural': 'Seguimientos de scouting',
                'ordering': ['is_done', 'due_on', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScoutingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('opposition', models.CharField(blank=True, max_length=160)),
                ('competition', models.CharField(blank=True, max_length=160)),
                ('technical_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tactical_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('physical_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mental_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('potential_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fit_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommendation', models.CharField(choices=[('sign', 'Fichar'), ('follow', 'Seguir'), ('discard', 'Descartar'), ('wait', 'Esperar')], default='wait', max_length=16)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informe de scouting',
                'verbose_name_plural': 'Informes de scouting',
                'ordering': ['-observed_on', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScoutingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Nombre del jugador ojeado, aunque no exista como ficha local.', max_length=160)),
                ('subject_team_name', models.CharField(blank=True, help_text='Club actual o referencia del jugador.', max_length=160)),
                ('position', models.CharField(blank=True, max_length=60)),
                ('dominant_foot', models.CharField(blank=True, max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('target', 'Objetivo'), ('watchlist', 'En seguimiento'), ('active', 'Seguimiento activo'), ('review', 'Revisar'), ('discarded', 'Descartado'), ('signed', 'Firmado')], db_index=True, default='watchlist', max_length=24)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='medium', max_length=16)),
                ('next_review_on', models.DateField(blank=True, null=True)),
                ('budget_note', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jugador ojeado',
                'verbose_name_plural': 'Jugadores ojeados',
                'ordering': ['-priority', 'status', 'subject_name', '-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_scouting_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scouting_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_targets', to='football.player'),
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_targets', to='football.workspace'),
        ),
        migrations.AddField(
            model_name='scoutingreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutingreport',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='football.scoutingtarget'),
        ),
        migrations.AddField(
            model_name='scoutingfollowup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutingfollowup',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='football.scoutingtarget'),
        ),
        migrations.AddIndex(
            model_name='scoutingtarget',
            index=models.Index(fields=['workspace', 'status', 'priority'], name='scout_ws_status_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='scoutingtarget',
            index=models.Index(fields=['workspace', 'next_review_on'], name='scout_ws_review_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scoutingtarget',
            unique_together={('workspace', 'player', 'subject_name')},
        ),
        migrations.AddIndex(
            model_name='scoutingreport',
            index=models.Index(fields=['target', '-observed_on'], name='scout_report_target_idx'),
        ),
        migrations.AddIndex(
            model_name='scoutingreport',
            index=models.Index(fields=['target', 'recommendation'], name='scout_report_reco_idx'),
        ),
        migrations.AddIndex(
            model_name='scoutingfollowup',
            index=models.Index(fields=['target', 'is_done', 'due_on'], name='scout_followup_target_idx'),
        ),
    ]
