# Generated by Django 4.2.27 on 2026-07-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0145_scoutingfollowup_scoutingreport_scoutingtarget_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serviceaccesstoken',
            new_name='football_se_token_p_0068e2_idx',
            old_name='svtok_prefix_active_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceaccesstoken',
            new_name='football_se_user_id_4a94fc_idx',
            old_name='svtok_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='videoaigamecalibration',
            new_name='football_vi_team_id_91905d_idx',
            old_name='football_vi_team_id_3a3056_idx',
        ),
        migrations.RenameIndex(
            model_name='videoaigamecalibration',
            new_name='football_vi_video_i_81a502_idx',
            old_name='football_vi_video_i_b913e6_idx',
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='available_for_coach_tools',
            field=models.BooleanField(db_index=True, default=False, help_text='Si el ojeado puede aparecer en entrenos y en la pizarra del entrenador.'),
        ),
    ]
