# Generated by Django 4.2.27 on 2026-07-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0147_normalize_player_and_scouting_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='blocks_training',
            field=models.BooleanField(default=False, help_text='Marca si impide entrenar.'),
        ),
        migrations.AddField(
            model_name='playerinjuryrecord',
            name='is_recovered',
            field=models.BooleanField(default=False, help_text='Marca si la lesión ya está recuperada.'),
        ),
        migrations.CreateModel(
            name='InjuryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('milestone_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='football.playerinjuryrecord')),
            ],
            options={
                'verbose_name': 'Hito de lesión',
                'verbose_name_plural': 'Hitos de lesión',
                'ordering': ['position', 'milestone_date', 'id'],
            },
        ),
    ]
