# Generated by Django 4.2.27 on 2026-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0149_normalize_positions_and_feet'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='agent_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='player',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='player',
            name='current_club',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='player',
            name='has_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
