# Generated by Django 4.2.27 on 2026-07-23 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0150_player_agent_name_player_agent_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingTargetSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, help_text='Temporada, ej. 2025/2026.', max_length=40)),
                ('team', models.CharField(blank=True, help_text='Equipo/club en esa temporada.', max_length=160)),
                ('division', models.CharField(blank=True, help_text='División o categoría.', max_length=120)),
                ('matches_starter', models.PositiveSmallIntegerField(default=0, help_text='Partidos como titular.')),
                ('matches_completed', models.PositiveSmallIntegerField(default=0, help_text='Partidos completados.')),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_season_stats', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='football.scoutingtarget')),
            ],
            options={
                'verbose_name': 'Temporada de ojeo',
                'verbose_name_plural': 'Temporadas de ojeo',
                'ordering': ['-season', '-created_at', '-id'],
                'indexes': [models.Index(fields=['target', 'season'], name='scout_seasonstat_target_idx')],
            },
        ),
    ]
