# Generated by Django 4.2.27 on 2026-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0151_scoutingtargetseasonstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skin_tone',
            field=models.CharField(blank=True, help_text='Tono de piel para el avatar generado: light / medium / dark.', max_length=16),
        ),
    ]
