# Generated by Django 4.2.27 on 2026-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0153_normalize_player_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingtarget',
            name='agent_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='has_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
