# Generated by Django 4.2.27 on 2026-07-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0154_scoutingtarget_agent_name_scoutingtarget_agent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingtarget',
            name='discard_club',
            field=models.CharField(blank=True, help_text='Club que lo fichó, si el motivo es que fichó por otro.', max_length=160),
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='discard_reason',
            field=models.CharField(blank=True, choices=[('coach', 'Descartado por el entrenador'), ('signed_other', 'Fichó por otro club'), ('level', 'Nivel insuficiente'), ('economic', 'Motivo económico'), ('age', 'Edad'), ('physical', 'Lesión / condición física'), ('attitude', 'Actitud / comportamiento'), ('other', 'Otro')], db_index=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='scoutingtarget',
            name='status',
            field=models.CharField(choices=[('target', 'Objetivo'), ('watchlist', 'En seguimiento'), ('active', 'Seguimiento activo'), ('review', 'Revisar'), ('discarded', 'Descartado'), ('signed', 'Fichado'), ('signed_other', 'Fichado por otro equipo')], db_index=True, default='watchlist', max_length=24),
        ),
    ]
