# Generated by Django 4.2.27 on 2026-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0155_scoutingtarget_discard_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingtarget',
            name='discard_permanent',
            field=models.BooleanField(default=False, help_text='Descarte definitivo: no volver a por él.'),
        ),
    ]
