# Generated by Django 4.2.27 on 2026-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0156_scoutingtarget_discard_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='besoccer_url',
            field=models.URLField(blank=True, help_text='URL del perfil en BeSoccer.', max_length=300),
        ),
        migrations.AddField(
            model_name='player',
            name='preferente_profile_url',
            field=models.URLField(blank=True, help_text='URL del perfil del jugador en La Preferente (para autoactualizar stats).', max_length=300),
        ),
        migrations.AddField(
            model_name='player',
            name='transfermarkt_url',
            field=models.URLField(blank=True, help_text='URL del perfil en Transfermarkt.', max_length=300),
        ),
    ]
