# Generated by Django 4.2.27 on 2026-07-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0157_coachpitchboardlayout'),
        ('football', '0157_player_besoccer_url_player_preferente_profile_url_and_more'),
    ]

    operations = [
    ]
