# Generated by Django 4.2.27 on 2026-07-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0158_coachpitchboardlayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('lapreferente', 'La Preferente')], db_index=True, default='lapreferente', max_length=24)),
                ('season_label', models.CharField(db_index=True, max_length=16)),
                ('team_name', models.CharField(blank=True, max_length=160)),
                ('competition', models.CharField(blank=True, max_length=160)),
                ('external_name', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=60)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('starts', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('goals_conceded', models.IntegerField(blank=True, null=True)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_season_stats', to='football.player')),
                ('scouting_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_season_stats', to='football.scoutingtarget')),
            ],
            options={
                'verbose_name': 'Estadistica externa por temporada',
                'verbose_name_plural': 'Estadisticas externas por temporada',
                'ordering': ['-season_label'],
                'indexes': [models.Index(fields=['player', 'source', 'season_label'], name='extstat_player_idx'), models.Index(fields=['scouting_target', 'source', 'season_label'], name='extstat_target_idx')],
            },
        ),
    ]
