# Generated by Django 4.2.27 on 2026-07-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0160_scoutingpitchboardlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='federation_license_expires_at',
            field=models.DateField(blank=True, help_text='Caducidad de la licencia federativa (para avisos de renovación).', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='federation_license_number',
            field=models.CharField(blank=True, help_text='Nº licencia federativa (opcional).', max_length=80),
        ),
        migrations.AddField(
            model_name='player',
            name='license_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
