# Generated by Django 4.2.27 on 2026-07-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0161_player_federation_license_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('preferente_profile_url', models.URLField(blank=True, db_index=True, max_length=300)),
                ('transfermarkt_url', models.URLField(blank=True, db_index=True, max_length=300)),
                ('besoccer_url', models.URLField(blank=True, db_index=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Identidad de jugador',
                'verbose_name_plural': 'Identidades de jugador',
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_records', to='football.playeridentity'),
        ),
    ]
