# Generated by Django 4.2.27 on 2026-07-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0163_backfill_player_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_key',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
    ]
