# Generated by Django 4.2.27 on 2026-07-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0165_backfill_team_name_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('preferente_url', models.URLField(blank=True)),
                ('crest_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='football.club'),
        ),
    ]
