# Generated by Django 4.2.27 on 2026-07-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0167_backfill_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='transferred_at',
            field=models.DateField(blank=True, help_text='Fecha en que fichó por otro club (salida de la plantilla).', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='transferred_to_club',
            field=models.ForeignKey(blank=True, help_text='Club por el que fichó el jugador al salir de la plantilla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='football.club'),
        ),
    ]
