# Generated by Django 4.2.27 on 2026-07-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0168_player_transferred_at_player_transferred_to_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingtarget',
            name='signed_club',
            field=models.ForeignKey(blank=True, help_text='Club que fichó al ojeado, si el descarte es "fichó por otro" (autollenado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_signed', to='football.club'),
        ),
        migrations.AddField(
            model_name='scoutingtarget',
            name='subject_club',
            field=models.ForeignKey(blank=True, help_text='Club actual del ojeado, enlazado al catálogo (autollenado desde el texto).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_current', to='football.club'),
        ),
    ]
