# Generated by Django 4.2.27 on 2026-07-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0170_backfill_scouting_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='transferred_to_category',
            field=models.CharField(blank=True, help_text='Categoría/equipo dentro del club destino (ej. Senior, Cadete).', max_length=60),
        ),
    ]
