# Generated by Django 4.2.27 on 2026-07-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0171_player_transferred_to_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('name_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Orden por edad/nivel (0 = sin definir).')),
                ('game_format', models.CharField(blank=True, help_text='F7/F11 si aplica.', max_length=8)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='football.club')),
            ],
            options={
                'verbose_name': 'Categoría de club',
                'verbose_name_plural': 'Categorías de club',
                'ordering': ['club_id', 'order', 'name', 'id'],
                'unique_together': {('club', 'name_key')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='transferred_to_category_ref',
            field=models.ForeignKey(blank=True, help_text='Categoría destino (sub-entidad del club) del traspaso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='football.clubcategory'),
        ),
        migrations.AddField(
            model_name='team',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Categoría (sub-entidad del club) a la que pertenece este equipo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='football.clubcategory'),
        ),
    ]
