# Generated by Django 4.2.27 on 2026-07-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0174_task_methodology_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='agility_505_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='cmj_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salto CMJ en cm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='copenhagen_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='growth_velocity_cm_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Velocidad de crecimiento cm/año.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='maturation_status',
            field=models.CharField(blank=True, choices=[('', 'Sin definir'), ('pre_phv', 'Pre-PHV'), ('circa_phv', 'Circa-PHV'), ('post_phv', 'Post-PHV')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='maturity_offset_years',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Años respecto al PHV.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='session_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duración de sesión/partido en minutos.', null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='sprint_10m_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='sprint_20m_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='sprint_5m_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='wellness_fatigue',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Fatiga percibida 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='wellness_motivation',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Motivación 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='wellness_sleep',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sueño/descanso 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='wellness_soreness',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dolor muscular 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='wellness_stress',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estrés percibido 1-10.', null=True),
        ),
        migrations.AddField(
            model_name='playerphysicalmetric',
            name='yo_yo_ir1_m',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Yo-Yo IR1 en metros.', null=True),
        ),
        migrations.AlterField(
            model_name='playerphysicalmetric',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, help_text='RPE de la sesión 1-10', null=True),
        ),
        migrations.AlterField(
            model_name='playerphysicalmetric',
            name='wellness',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bienestar global 1-10', null=True),
        ),
    ]
