# Generated by Django 4.2.27 on 2026-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0177_backfill_physical_from_evaluations'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contract_end',
            field=models.DateField(blank=True, help_text='Fin de contrato (para avisos de renovación).', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_notes',
            field=models.CharField(blank=True, help_text='Notas de contrato/ficha (salario, bonus, vinculación…).', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_start',
            field=models.DateField(blank=True, help_text='Inicio de contrato/vinculación.', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='release_clause',
            field=models.CharField(blank=True, help_text='Cláusula de rescisión (texto libre, ej. "50.000 €").', max_length=80),
        ),
    ]
