# Generated by Django 4.2.27 on 2026-07-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0178_player_contract_end_player_contract_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En curso'), ('done', 'Cumplido')], db_index=True, default='pending', max_length=16)),
                ('target_date', models.DateField(blank=True, help_text='Fecha objetivo (opcional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='football.player')),
            ],
            options={
                'verbose_name': 'Objetivo de jugador',
                'verbose_name_plural': 'Objetivos de jugador',
                'ordering': ['status', 'target_date', '-created_at', '-id'],
            },
        ),
    ]
