# Generated by Django 4.2.27 on 2026-07-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0181_backfill_paid_modules_grandfather'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerevaluation',
            name='parameter_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
