# Generated by Django 4.2.27 on 2026-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0183_backfill_benagalbon_2025_26_standings'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hair_color',
            field=models.CharField(blank=True, help_text='Color de pelo del avatar en hex (ej. #4a2d1a).', max_length=16),
        ),
        migrations.AddField(
            model_name='player',
            name='skin_grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Grado de piel 1 (muy clara) a 6 (muy oscura) para el avatar.', null=True),
        ),
    ]
