# Generated by Django 4.2.27 on 2026-07-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0185_backfill_discarded_scout_players_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_federative_license',
            field=models.BooleanField(db_index=True, default=False, help_text='Tiene ficha federativa (licencia oficial de la temporada).'),
        ),
    ]
