# Generated by Django 4.2.27 on 2026-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0186_player_has_federative_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_generated',
            field=models.ImageField(blank=True, help_text='Avatar generado (face-swap) cacheado; lo produce el comando generate_player_avatars.', null=True, upload_to='player-avatars/'),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar_source_key',
            field=models.CharField(blank=True, help_text='Hash de las entradas del avatar generado (foto+peinado+color+piel+altura).', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='hairstyle',
            field=models.CharField(blank=True, choices=[('corto', 'Corto'), ('medio', 'Medio'), ('rizado', 'Rizado')], help_text='Forma del peinado del avatar (corto/medio/rizado).', max_length=16),
        ),
    ]
