# Generated by Django 4.2.27 on 2026-07-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0187_player_avatar_generated_player_avatar_source_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hairstyle',
            field=models.CharField(blank=True, choices=[('corto', 'Corto'), ('medio', 'Medio'), ('rizado', 'Rizado'), ('largo', 'Largo')], help_text='Forma del peinado del avatar (corto/medio/rizado).', max_length=16),
        ),
    ]
