# Generated by Django 4.2.27 on 2026-07-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0188_alter_player_hairstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hairstyle',
            field=models.CharField(blank=True, choices=[('corto', 'Corto'), ('medio', 'Medio'), ('rizado', 'Rizado'), ('largo', 'Largo'), ('rapado', 'Rapado')], help_text='Forma del peinado del avatar (corto/medio/rizado).', max_length=16),
        ),
    ]
