# Generated by Django 4.2.27 on 2026-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0192_merge_embedded_blobs_and_standings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserrole',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuserrole',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
