# Generated by Django 4.2.27 on 2026-07-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0197_backfill_match_lineups'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('kit_titular', 'Avatar equipación titular'), ('kit_visitante', 'Avatar equipación visitante'), ('kit_turquesa', 'Avatar entreno turquesa'), ('kit_blanca', 'Avatar entreno blanca'), ('chandal', 'Avatar chándal'), ('lesionado', 'Avatar lesionado'), ('gk_azul', 'Avatar portero azul'), ('gk_negra', 'Avatar portero negra'), ('gk_magenta', 'Avatar portero magenta'), ('chapa_local', 'Chapa local'), ('chapa_away', 'Chapa visitante'), ('chapa_gk', 'Chapa portero'), ('foto', 'Foto')], max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='player-assets/')),
                ('source_key', models.CharField(blank=True, help_text='Hash de las entradas (foto+kit+características) para regenerar solo si cambian.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='football.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'kind'], name='football_pl_player__18240b_idx')],
                'unique_together': {('player', 'kind')},
            },
        ),
    ]
