# Generated by Django 4.2.27 on 2026-07-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0198_player_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stats_source',
            field=models.CharField(blank=True, choices=[('', 'Sin datos'), ('live', 'En vivo'), ('manual', 'Manual'), ('result_only', 'Solo resultado')], default='', help_text='Fuente única de datos del partido (evita doble conteo): en vivo, manual, solo resultado o sin datos.', max_length=16),
        ),
    ]
