# Generated by Django 4.2.27 on 2026-07-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0198_player_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontask',
            name='block',
            field=models.CharField(choices=[('activation', 'Activación'), ('physical_prep', 'Preparación física'), ('conditioning', 'Condicionante'), ('main_1', 'Principal 1'), ('main_2', 'Principal 2'), ('set_pieces', 'ABP'), ('recovery', 'Vuelta calma'), ('video', 'Vídeo')], default='main_1', max_length=30),
        ),
        migrations.AlterField(
            model_name='taskstudiotask',
            name='block',
            field=models.CharField(choices=[('activation', 'Activación'), ('physical_prep', 'Preparación física'), ('conditioning', 'Condicionante'), ('main_1', 'Principal 1'), ('main_2', 'Principal 2'), ('set_pieces', 'ABP'), ('recovery', 'Vuelta calma'), ('video', 'Vídeo')], default='main_1', max_length=30),
        ),
    ]
