# Generated by Django 4.2.27 on 2026-07-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0199_add_physical_prep_block'),
        ('football', '0200_infer_match_stats_source'),
    ]

    operations = [
    ]
