# Generated by Django 4.2.27 on 2026-07-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0201_merge_20260728_1023'),
        ('football', '0201_merge_20260728_1025'),
    ]

    operations = [
    ]
