# Generated by Django 4.2.27 on 2026-07-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0202_merge_20260728_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTaskParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_participations', to='football.player')),
                ('session_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='football.sessiontask')),
            ],
            options={
                'indexes': [models.Index(fields=['player'], name='football_se_player__c8545c_idx'), models.Index(fields=['session_task'], name='football_se_session_e24cbe_idx')],
                'unique_together': {('session_task', 'player')},
            },
        ),
    ]
