# Generated by Django 4.2.27 on 2026-07-28 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0203_session_task_participation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('convocatoria', 'Convocatoria'), ('general', 'Aviso')], default='general', max_length=24)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_notifications', to='football.match')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_notifications', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_notifications', to='football.team')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_notifications', to='football.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_user', 'is_read', '-created_at'], name='football_pl_target__a04abd_idx'), models.Index(fields=['target_user', 'kind', 'match'], name='football_pl_target__e49d0c_idx')],
            },
        ),
    ]
