# Generated by Django 4.2.27 on 2026-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0204_playernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playernotification',
            name='kind',
            field=models.CharField(choices=[('convocatoria', 'Convocatoria'), ('alineacion', 'Alineación'), ('general', 'Aviso')], default='general', max_length=24),
        ),
    ]
