# Generated by Django 4.2.27 on 2026-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0205_alter_playernotification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
    ]
