# Generated by Django 4.2.27 on 2026-07-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0211_fix_mislinked_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RivalPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='lapreferente', max_length=20)),
                ('source_player_id', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('preferente_profile_url', models.CharField(blank=True, default='', max_length=300)),
                ('full_name', models.CharField(max_length=140)),
                ('alias', models.CharField(blank=True, default='', max_length=80)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, default='', max_length=300)),
                ('position', models.CharField(blank=True, default='', max_length=60)),
                ('line', models.CharField(blank=True, default='', max_length=8)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('season_label', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_appearances', to='football.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rival_players', to='football.team')),
            ],
            options={
                'verbose_name': 'Jugador rival',
                'verbose_name_plural': 'Jugadores rival',
                'ordering': ['line', 'number', 'full_name'],
                'indexes': [models.Index(fields=['team', 'is_active'], name='rivalplayer_team_active_idx'), models.Index(fields=['source', 'source_player_id'], name='rivalplayer_source_idx')],
            },
        ),
    ]
