# Generated by Django 4.2.27 on 2026-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0212_rivalplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='is_session_template',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
