# Generated by Django 4.2.27 on 2026-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0214_fix_session_template_microcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='kit_primary_color',
            field=models.CharField(blank=True, default='', help_text='Color principal del kit (hex). Derivado del escudo por defecto; editable.', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='kit_secondary_color',
            field=models.CharField(blank=True, default='', help_text='Color secundario del kit (hex).', max_length=7),
        ),
    ]
