# Generated by Django 4.2.27 on 2026-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0215_team_kit_primary_color_team_kit_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='traits',
            field=models.JSONField(blank=True, default=list, help_text='Rasgos/preferencias del jugador (estilo FM): claves de PLAYER_TRAITS.'),
        ),
    ]
