# Generated by Django 4.2.27 on 2026-07-31 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0217_player_squad_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='portal_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Excepciones de visibilidad del portal SOLO para este jugador (mismo formato que PlayerPortalPolicy.sections). Vacío = manda la política del club. Sin interfaz a propósito: es la salida para el caso raro, no la forma normal de configurar.'),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='published_comments_to_player',
            field=models.BooleanField(default=False, help_text='Al publicar, incluir también los comentarios del cuerpo técnico.'),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='published_to_player',
            field=models.BooleanField(default=False, help_text='Publicada al jugador. Cerrar la evaluación NO la publica: es un gesto aparte.'),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='published_to_player_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='published_to_player_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_player_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlayerPortalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(blank=True, default=dict, help_text='Mapa sección -> estado (hidden/visible/published_only). Lo que falte cae al valor por defecto.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, help_text='Vacío = regla del club. Con equipo = regla de esa categoría, que pisa a la del club.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_portal_policies', to='football.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_portal_policies_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_portal_policies', to='football.workspace')),
            ],
            options={
                'verbose_name': 'Política del portal del jugador',
                'verbose_name_plural': 'Políticas del portal del jugador',
            },
        ),
        migrations.AddConstraint(
            model_name='playerportalpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('workspace',), name='uniq_player_portal_policy_club'),
        ),
        migrations.AddConstraint(
            model_name='playerportalpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('workspace', 'team'), name='uniq_player_portal_policy_team'),
        ),
    ]
