# Generated by Django 4.2.27 on 2026-07-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0218_portal_jugador_politica'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Jugador al que se vincula la cuenta al aceptar la invitación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='football.player'),
        ),
    ]
