# Generated by Django 4.2.27 on 2026-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0219_invitacion_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerevaluation',
            name='author_kind',
            field=models.CharField(choices=[('staff', 'Cuerpo técnico'), ('self', 'Autovaloración del jugador')], db_index=True, default='staff', help_text='Quién la firma. Sólo las del cuerpo técnico entran en la media.', max_length=12),
        ),
    ]
