# Generated by Django 4.2.27 on 2026-08-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0228_match_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='build',
            field=models.CharField(blank=True, choices=[('delgado', 'Delgado'), ('normal', 'Normal'), ('fuerte', 'Fuerte'), ('espigado', 'Espigado')], help_text='Complexion del jugador: decide la figura del avatar.', max_length=16),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Marca si el partido ya se cerró y no debe seguir apareciendo como pendiente en convocatoria.'),
        ),
    ]
