# Generated by Django 4.2.27 on 2026-08-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0229_player_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceteam',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcar si esta temporada no se usa. No borra nada: deja de salir en los selectores y en los recuentos del club, y su histórico se conserva.'),
        ),
    ]
