# Generated by Django 4.2.27 on 2026-08-03 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0231_playermatchreportarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('formation', models.CharField(blank=True, default='', help_text='Ej. 1-4-3-3', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('lineup_data', models.JSONField(blank=True, default=dict, help_text="{'starters': [...], 'bench': [...]}")),
                ('rival_lineup_data', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False, help_text='El planteamiento con el que se empieza.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tactical_plans', to=settings.AUTH_USER_MODEL)),
                ('rival_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_rival_tactical_plans', to='football.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactical_plans', to='football.team')),
            ],
            options={
                'ordering': ['-is_default', '-updated_at', 'name'],
                'unique_together': {('team', 'name')},
            },
        ),
    ]
