# Generated by Django 4.2.27 on 2026-08-04 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0233_plan_fases'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('ataque', 'Ataque'), ('defensa', 'Defensa'), ('transicion', 'Transición'), ('abp', 'Balón parado')], default='ataque', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('steps_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tactical_plays', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactical_plays', to='football.team')),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
                'unique_together': {('team', 'name')},
            },
        ),
    ]
