# Generated by Django 4.2.27 on 2026-08-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0234_tactical_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontask',
            name='tactical_play',
            field=models.ForeignKey(blank=True, help_text='La jugada del equipo que se entrena en esta tarea.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_tasks', to='football.tacticalplay'),
        ),
        migrations.AddField(
            model_name='tacticalplay',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacticalplay',
            name='published_to_players',
            field=models.BooleanField(default=False),
        ),
    ]
