# Generated by Django 4.2.27 on 2026-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0235_jugada_en_tarea_y_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='plays',
            field=models.ManyToManyField(blank=True, help_text='Jugadas que se enseñan en la charla de este partido.', related_name='matches', to='football.tacticalplay'),
        ),
    ]
