# Generated by Django 4.2.27 on 2026-08-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0236_jugadas_del_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='tactical_play',
            field=models.ForeignKey(blank=True, help_text='La jugada del playbook que este clip ejecuta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips', to='football.tacticalplay'),
        ),
    ]
