# Generated by Django 4.2.27 on 2026-08-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0237_jugada_en_el_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamNameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150)),
                ('alias_key', models.CharField(db_index=True, max_length=150, unique=True)),
                ('source', models.CharField(blank=True, default='', help_text='De dónde vino esa grafía (universo, preferente, fusión…)', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_aliases', to='football.team')),
            ],
            options={
                'verbose_name': 'alias de equipo',
                'verbose_name_plural': 'alias de equipos',
                'ordering': ['alias'],
            },
        ),
    ]
