# Generated by Django 4.2.27 on 2026-08-04 13:42
"""
Ata la grabación a su partido (y marca el saque) para convertir el registro en clips.

OJO: esto se escribió como tres `AddField` normales y **tumbó el despliegue**: en producción la
columna `match_id` YA existía, Postgres respondió "column already exists" y el pre-deploy se cayó
entero. Pasa cuando dos ventanas tocan el mismo modelo a la vez.

Ahora cada columna se añade **sólo si falta**, mirando antes qué hay en la base. El estado que ve
Django es el mismo (`state_operations`); lo que cambia es lo que se ejecuta contra la base, que ya
se puede aplicar dos veces sin romperse.
"""
from django.db import migrations, models
import django.db.models.deletion


COLUMNAS = {
    'match_id': 'integer NULL REFERENCES "football_match" ("id") DEFERRABLE INITIALLY DEFERRED',
    'kickoff_ms': 'integer NOT NULL DEFAULT 0',
    'second_half_ms': 'integer NOT NULL DEFAULT 0',
}


def _anadir_lo_que_falte(apps, schema_editor):
    """Añade cada columna sólo si no está. Vale igual en Postgres y en SQLite."""
    conexion = schema_editor.connection
    with conexion.cursor() as cursor:
        existentes = {
            fila.name
            for fila in conexion.introspection.get_table_description(cursor, 'football_rivalvideo')
        }
        for columna, definicion in COLUMNAS.items():
            if columna in existentes:
                continue
            if conexion.vendor != 'postgresql' and columna == 'match_id':
                definicion = 'integer NULL REFERENCES "football_match" ("id")'
            cursor.execute(f'ALTER TABLE "football_rivalvideo" ADD COLUMN "{columna}" {definicion}')
        if conexion.vendor == 'postgresql':
            cursor.execute(
                'CREATE INDEX IF NOT EXISTS "football_rivalvideo_match_id_idx" '
                'ON "football_rivalvideo" ("match_id")'
            )


def _atras(apps, schema_editor):
    """Marcha atrás: las columnas se quedan. Borrarlas se llevaría datos que quizá no pusimos."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0238_alias_de_equipo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(_anadir_lo_que_falte, _atras)],
            state_operations=[
                migrations.AddField(
                    model_name='rivalvideo',
                    name='kickoff_ms',
                    field=models.PositiveIntegerField(default=0, help_text='Milisegundo del vídeo en el que se pita el inicio (minuto 0 del partido).'),
                ),
                migrations.AddField(
                    model_name='rivalvideo',
                    name='match',
                    field=models.ForeignKey(blank=True, help_text='El partido que recoge esta grabación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_videos', to='football.match'),
                ),
                migrations.AddField(
                    model_name='rivalvideo',
                    name='second_half_ms',
                    field=models.PositiveIntegerField(default=0, help_text='Milisegundo del vídeo en el que arranca la segunda parte. 0 = grabación continua.'),
                ),
            ],
        ),
    ]
