# Generated by Django 4.2.27 on 2026-08-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0238_alias_de_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rivalvideo',
            name='kickoff_ms',
            field=models.PositiveIntegerField(default=0, help_text='Milisegundo del vídeo en el que se pita el inicio (minuto 0 del partido).'),
        ),
        migrations.AddField(
            model_name='rivalvideo',
            name='match',
            field=models.ForeignKey(blank=True, help_text='El partido que recoge esta grabación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_videos', to='football.match'),
        ),
        migrations.AddField(
            model_name='rivalvideo',
            name='second_half_ms',
            field=models.PositiveIntegerField(default=0, help_text='Milisegundo del vídeo en el que arranca la segunda parte. 0 = grabación continua.'),
        ),
    ]
