# Generated by Django 4.2.27 on 2026-08-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0239_video_atado_al_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingtarget',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Equipo/categoría para la que se ojea. Vacío = del club, visible en todas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_targets', to='football.team'),
        ),
    ]
