# Generated by Django 4.2.27 on 2026-08-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0240_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontask',
            name='task_family',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Familia de la tarea: rondo, juego de posición, circuito… (derivado del JSON)', max_length=30),
        ),
    ]
