# Generated by Django 4.2.27 on 2026-08-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    # Dependía de una 0240_team_division que NO existe en el repositorio: la cadena se rompía y
    # `migrate` fallaba entero, así que el despliegue se habría caído al llegar a producción.
    # Se engancha a la última real y se renumera para que el orden quede claro.
    dependencies = [
        ('football', '0241_direccion_existente_al_equipo_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontask',
            name='task_family',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Familia de la tarea: rondo, juego de posición, circuito… (derivado del JSON)', max_length=30),
        ),
    ]
