# Generated by Django 4.2.27 on 2026-08-05 19:30

from django.db import migrations, models


def rellenar_con_lo_ya_entrenado(apps, schema_editor):
    """Cuenta el uso que YA existe, en vez de empezar de cero.

    Cada tarea copiada de la biblioteca guarda de cuál salió (`meta.library_source_task_id`),
    así que una temporada entera de sesiones es señal disponible: sin esto, el recomendador
    tardaría meses en saber qué usa de verdad este entrenador.
    """
    SessionTask = apps.get_model('football', 'SessionTask')
    try:
        from football.library_repositories import LIBRARY_MICROCYCLE_MARKER
    except Exception:
        return

    from django.db.models import Q

    usos = {}
    puestas = (
        # select_related SOLO de la sesión: pedir también el microciclo y a la vez diferirlo
        # con only() es contradictorio y Django lo rechaza. El microciclo se filtra por JOIN.
        SessionTask.objects.select_related('session')
        .filter(deleted_at__isnull=True)
        .exclude(
            Q(session__microcycle__notes__icontains=LIBRARY_MICROCYCLE_MARKER)
            | Q(session__microcycle__title__istartswith='Biblioteca ')
        )
        .only('id', 'task_layout_light', 'session__session_date')
    )
    for tarea in puestas.iterator(chunk_size=300):
        ligero = tarea.task_layout_light if isinstance(tarea.task_layout_light, dict) else {}
        meta = ligero.get('meta') if isinstance(ligero.get('meta'), dict) else {}
        try:
            origen = int(meta.get('library_source_task_id') or 0)
        except Exception:
            origen = 0
        if not origen:
            continue
        fecha = getattr(getattr(tarea, 'session', None), 'session_date', None)
        veces, ultima = usos.get(origen, (0, None))
        usos[origen] = (veces + 1, max(fecha, ultima) if (fecha and ultima) else (fecha or ultima))

    tocadas = 0
    for origen, (veces, ultima) in usos.items():
        actualizadas = SessionTask.objects.filter(id=origen).update(
            veces_usada=veces, usada_por_ultima_vez=ultima
        )
        tocadas += actualizadas
    if tocadas:
        print(f'  tareas de biblioteca con memoria de uso: {tocadas}')


def atras(apps, schema_editor):
    """Se van con las columnas; no hay nada que deshacer a mano."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0243_indexar_biblioteca_para_el_recomendador'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontask',
            name='usada_por_ultima_vez',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessiontask',
            name='veces_usada',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    
        migrations.RunPython(rellenar_con_lo_ya_entrenado, atras),
    ]
