# Generated by Django 4.2.27 on 2026-08-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0244_memoria_de_uso_de_la_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTrainerRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.PositiveSmallIntegerField(default=0, help_text='Posición en la lista propuesta (1 = la primera)')),
                ('score', models.FloatField(default=0.0)),
                ('motivos', models.JSONField(blank=True, default=list)),
                ('propuesta_en', models.DateTimeField(auto_now=True)),
                ('veces_propuesta', models.PositiveIntegerField(default=1)),
                ('usada', models.BooleanField(default=False)),
                ('usada_en', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_trainer_recomendaciones', to='football.trainingsession')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trainer_recomendaciones', to='football.sessiontask')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_trainer_recomendaciones', to='football.team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'usada'], name='football_ai_team_id_3ad528_idx'), models.Index(fields=['team', '-propuesta_en'], name='football_ai_team_id_74293d_idx')],
                'unique_together': {('session', 'task')},
            },
        ),
    ]
