# Generated by Django 4.2.27 on 2026-08-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0245_registro_de_recomendaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontaskcollection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='football.sessiontaskcollection'),
        ),
    ]
