# Generated by Django 4.2.27 on 2026-08-06 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0246_subcarpetas_de_biblioteca'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('player', 'Jugador'), ('team', 'Equipo')], db_index=True, max_length=12)),
                ('reason', models.CharField(blank=True, help_text='Por qué lo sigues.', max_length=240)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_watches', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_watches', to='football.player')),
                ('rival_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_watches', to='football.rivalplayer')),
                ('season', models.ForeignKey(blank=True, help_text='Temporada en la que se sigue. Al cerrarla, la lista se archiva.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='football.workspaceseason')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_watches', to='football.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_watches', to='football.workspace')),
            ],
            options={
                'verbose_name': 'Seguimiento de temporada',
                'verbose_name_plural': 'Seguimientos de temporada',
                'ordering': ['kind', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SeasonWatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_watch_notes', to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='football.seasonwatch')),
            ],
            options={
                'verbose_name': 'Anotación de seguimiento',
                'verbose_name_plural': 'Anotaciones de seguimiento',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='seasonwatch',
            index=models.Index(fields=['workspace', 'season', 'is_active'], name='swatch_ws_season_idx'),
        ),
    ]
