# Generated by Django 4.2.27 on 2026-08-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0248_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocationrecord',
            name='call_time',
            field=models.TimeField(blank=True, help_text='Hora de citación (llegada al campo).', null=True),
        ),
        migrations.AddField(
            model_name='convocationrecord',
            name='kit_choice',
            field=models.CharField(blank=True, help_text='Equipación: titular / visitante / turquesa / blanca.', max_length=20),
        ),
    ]
