# Generated by Django 4.2.27 on 2026-08-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0249_convocatoria_citacion_y_equipacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocationrecord',
            name='absence_reasons',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
