# Generated by Django 4.2.27 on 2026-08-08 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0250_convocatoria_motivo_no_convocado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBoardShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, default='', max_length=64)),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('hecha', 'Hecha'), ('rendida', 'Rendida tras varios intentos')], db_index=True, default='pendiente', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=400)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_try_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('leased_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_shot', to='football.sessiontask')),
            ],
            options={
                'verbose_name': 'Foto HD de pizarra',
                'verbose_name_plural': 'Fotos HD de pizarra',
                'indexes': [models.Index(fields=['state', 'next_try_at'], name='taskshot_cola_idx')],
            },
        ),
    ]
